### ISSUE TITLE
Should ProxyQuantityFactory be removed?

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#106]
@keilw made the following comment in #104:

>  `ProxyQuantityFactory` is only a backup implementation, the default `ServiceProvider` does not use it and I cannot say, if there is any situation where it has a key benefit over `DefaultQuantityFactory`?

@desruisseaux commented later in the same issue:

> SIS implements `QuantityFactory` using proxies, and the result of arithmetic operations is for example `Length` rather than `Quantity<Length>`.

**Comment by desruisseaux** [comment]
I'm neutral on `ProxyQuantityFactory` in Indriya; no objection if anyone want to remove it.

**Comment by keilw** [comment]
I moved both the latest version of `ProxyQuantityFactory` and the JUnit test into uom-se. Let's keep them there, as it has been there already and prune it from the new RI for now. Should there be a situation in a future version that allows multiple implementations to interact under the same module/class path, we could revive/port it if necessary.
