### ISSUE TITLE
Make "1/x" parseable

### ISSUE THREAD

**Issue by snowwits** [unitsofmeasurement/indriya#114]
It seems counter-intuitive that the unit "1/s" (Hertz) is not parseable.

"one/s" is parsed correctly. The resulting unit however is formatted as "1/s". And the common user would not come up with the idea to use "one" instead of "1".

The problem probably exists for all "1/x" unit strings (where "x" stands for some valid unit).

**Example**
```kotlin

@Test
fun parse_hertz() {
    assertThrows<MeasurementParseException> {
        ServiceProvider.current().formatService.unitFormat.parse("1/s")
    }

    val onePerSecond = ServiceProvider.current().formatService.unitFormat.parse("one/s")
    println(onePerSecond)
}

>>> 1/s
```
(Kotlin, Junit 5)

**Comment by keilw** [comment]
This is somewhat along the lines of https://github.com/unitsofmeasurement/indriya/issues/103, but using "1" as symbol for the constant `ONE` has totally unpredictable side-effects and used to break everything when last attempted.

**Comment by snowwits** [comment]
Yeah, I imagine. But maybe this special case can be handled in the `SimpleUnitFormat.DefaultFormat#parseProductUnit` method.

**Comment by keilw** [comment]
Not sure, if it'll work for `SimpleUnitFormat`, but see `EBNFFormatTest.testParseInverses()` every unit except `ONE/1` works parsed by `EBNFUnitFormat`.

I have not tried it in Kotlin, but I trust `ServiceProvider.current().formatService.unitFormat("EBNF").parse("1/s")` should work. That way you can parse it. We'll see, if SimpleUnitFormat can also be addressed somehow.

**Comment by snowwits** [comment]
Yeah, `EBNFUnitFormatis` able to parse "1/s". Thanks for that information. Thanks for trying to enable it for the `SimpleUnitFormat` as well.

```kotlin
@Test
fun parseEBNF_hertz() {
    val onePerSecond = ServiceProvider.current().formatService.getUnitFormat("EBNF").parse("1/s")
    println(onePerSecond)

    assertTrue(Units.HERTZ.isCompatible(onePerSecond))
}

>>>
1/s
```

However, `EBNFUnitFormatis` is for example not able to parse custom units like "kWh":

```kotlin
val WATT_HOUR: Unit<Energy> = TransformedUnit("Wh", Units.JOULE, RationalConverter(3600, 1))
val KILO_WATT_HOUR: Unit<Energy> = MetricPrefix.KILO(WATT_HOUR)

@Test
fun parseEBNF_kwh() {
    ServiceProvider.current().formatService.getUnitFormat("EBNF").label(KILO_WATT_HOUR, "kWh")
    assertThrows<MeasurementParseException> {
        try {
            ServiceProvider.current().formatService.getUnitFormat("EBNF").parse("kWh")
        } catch (e: MeasurementParseException) {
            e.printStackTrace()
            throw e
        }
    }
}

>>>
javax.measure.format.MeasurementParseException: tech.units.indriya.internal.format.TokenException: 
	at tech.units.indriya.format.EBNFUnitFormat.parse(EBNFUnitFormat.java:267)
	at tech.units.indriya.format.EBNFUnitFormat.parse(EBNFUnitFormat.java:276)
	at tech.units.indriya.format.EBNFUnitFormat.parse(EBNFUnitFormat.java:280)
...
```

However, the default unit format is able to parse custom units like "kWh":

```kotlin
@Test
fun parseDefault_kwh() {
    ServiceProvider.current().formatService.unitFormat.label(KILO_WATT_HOUR, "kWh")
    val kwh = ServiceProvider.current().formatService.unitFormat.parse("kWh")
    println(kwh)

    assertEquals(KILO_WATT_HOUR, kwh)
}

>>>
kWh
```

Should I open an issue for that as well? Or am I doing something wrong?

**Comment by keilw** [comment]
It should work without using label(), but it seems when the new Prefix was applied, some prefixes are no longer recognized.

**Comment by keilw** [comment]
So `EBNFUnitFormat `and others like `UCUMFormat `in extension modules have no problem parsing 1/s or similar. I guess as of now `SimpleUnitFormat `has a few limitations and it would exceed the scope of the current release to address those in a safe way with little side-effects. We may revisit this at a later point.
