### ISSUE TITLE
Improve exception message of MeasurementParseException("unexpected token") in SimpleUnitFormat.DefaultFormat.parseProductUnit

### ISSUE THREAD

**Issue by snowwits** [unitsofmeasurement/indriya#116]
The exception message of the `MeasurementParseException` if an unexpected token is encountered in `SimpleUnitFormat.DefaultFormat#parseProductUnit` should be improved.

It would be helpful if instead of the int value of the "unexpected token", a human readable name of the unexpected token (for example the token variable name) would be added to the message.

Actual:
```java

// SimpleUnitFormat line 554
throw new MeasurementParseException("unexpected token " + token, pos.getIndex());
```

Desired:
```java

private static final String[] TOKEN_NAMES = {"EOF", "IDENTIFIER", ... };

private static String getTokenName(int token) {
    return TOKEN_NAMES[token]
}

...

throw new MeasurementParseException("unexpected token " + getTokenName(token), pos.getIndex());
```

**Comment by keilw** [comment]
The easiest way to solve this was to turn the token into an enum ;-)

**Comment by snowwits** [comment]
Sure. I just thought you had explicitly chosen int flags over Enums because of performance. That's why stayed on that path with my suggestion. But yeah, Enums are well suited for those kind of things. :)
