### ISSUE TITLE
NumberQuantity types should also widen for numeric multiplication and division

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#117]
Same as issue #67, but also applied to the numeric methods `multiply(Number)` and `divide(Number)`.

**Comment by thodorisbais** [comment]
So, if I get it right, what is only pending here is the modification of `applyMultiplicativeNumberOperation` function, right?

**Comment by thodorisbais** [comment]
Status update: created a PR (#191), waiting for review.

**Comment by thodorisbais** [comment]
Closed with #191 .
