### ISSUE TITLE
Attribute TimedData#name can't be set

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#119]
`TimedData` implements `Nameable`, but the attribute `name` isn't available to be set through the constructor, factory method `of`, or a setter.

Also, the property isn't `final`.

Given the comment in the Javadoc that `TimedData` should be immutable, it should probably be available as an optional parameter in the constructor and the factory method, not through a setter method, and furthermore made `final`. Can somebody confirm this?

**Comment by keilw** [comment]
I'm not even sure, if the name is correct on that level?
It may be better on a collecting object like `TimeSeries` or similar see the Wikipedia article from the JavaDoc, wdyt?

**Comment by filipvanlaenen** [comment]
If there's no use for the attribute, maybe we should remove it (and remove `Nameable` as an interface `TimedData` implements)?

**Comment by keilw** [comment]
The idea comes from OSGi Measurements: https://wiki.searchtechnologies.com/javadoc/osgi/osgi-javadoc-v41/org/osgi/util/measurement/State.html

**Comment by filipvanlaenen** [comment]
OSGi `State` has the `name` in the constructor.

**Comment by keilw** [comment]
We should probably do similar in the `of()` method and protected constructor. Might also make it `final `then.

**Comment by keilw** [comment]
As mentioned it's meant to be an equivalent to OSGi Measurement `State`.

**Comment by keilw** [comment]
I demonstrated with a rather small `TimedQuantityData` class on top (similar to `QuantityRange`, maybe `TimedData` could have been part of the Indriya SPI as well, but the relationship to time and temporal is why it ended up here) what the intention of the OSGi State equivalent is.
