### ISSUE TITLE
Parsing of unit strings with single trailing asterisk leads to StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by snowwits** [unitsofmeasurement/indriya#131]
**Problem**
`SimpleUnitFormat.getInstance().parse(CharSequence)` throws a `StringIndexOutOfBoundsException` when trying to parse a unit string with a single trailing `*`.

**Example**
```kotlin
@Test
fun parseTrailingAsterisk() {
   val ex: StringIndexOutOfBoundsException = assertThrows {
       SimpleUnitFormat.getInstance().parse("m*")
    }
    assertEquals("String index out of range: 2", ex.message)
}
```

**Analysis**
The `StringIndexOutOfBoundsException` is thrown in `SimpleUnitFormat.nextToken(CharSequence, Parseposition)` at `SimpleUnitFormat:573`:

`SimpleUnitFormat:572-573`
```java
        } else if (c == '*') {
          char c2 = csq.charAt(pos.getIndex() + 1);
```

If the last character of the given CharSequence `csq` is an `*`, there is no next char and `csq.charAt(pos.getIndex() + 1)` throws an `StringIndexOutOfBoundsException `.

**Proposed solution**
This illegal input should be handled better: A `MeasurementParseException` with a useful message should be thrown.

----

*EDIT:* I closed this by accident. Have reopened it.

**Comment by keilw** [comment]
I guess it only happens in SimpleUnitFormat, or have you reproduced it in other implementations?

**Comment by snowwits** [comment]
Yes. `EBNFFormat` throws a helpful exception: `javax.measure.format.MeasurementParseException: tech.units.indriya.internal.format.TokenException: Encountered "<EOF>" at line 1, column 2. ...`

`LocalFormat` seems to be not in a working state at the moment, - i tires to parse it as a compound expression and then throws an `UnsupportedOperationException("Compound units not supported")`. Correct me if I'm wrong but I think it's not fully implemented yet.

**Comment by keilw** [comment]
What do you mean with Compound expression? The idea of a `CompoundUnit` was discussed, but the way it is supposed to be supported is not yet implemented. The rest should work.

**Comment by snowwits** [comment]
As I said, I think the `LocalFormat` is not working in the current SNAPSHOT (probably because -as you said - CompoundUnit is not implemented fully yet).

That's why I cannot verify if the problem also occurs in the `LocalFormat`.

**Comment by keilw** [comment]
It's been like that since uom-se. https://github.com/unitsofmeasurement/indriya/issues/34 has already been created to combine some of the functionalities where possible.
