### ISSUE TITLE
BinaryPrefixes not formatted properly by SimpleUnitFormat

### ISSUE THREAD

**Issue by snowwits** [unitsofmeasurement/indriya#132]
**Problem**
`SimpleUnitFormat` does not recognize `BinaryPrefix`es when it comes to formatting.

**Example Kotlin JUnit test**
```kotlin
@Test
fun addKibiByte() {
    val bit = BaseUnit<Dimensionless>("bit", QuantityDimension.NONE)
    val byte = TransformedUnit<Dimensionless>("byte", bit, RationalConverter(8, 1))
    val kibiByte = BinaryPrefix.KIBI(byte)
    println(kibiByte)
    SimpleUnitFormat.getInstance().label(kibiByte, kibiByte.toString())
}

>>> [byte?]
>>> java.lang.IllegalArgumentException: Label: [byte?] is not a valid identifier.
```

**Analysis**
The question is: Why is `kibiByte.toString()` = `[byte?]` when it should be `kibibyte`?

`AbstractUnitFormat.toString()` is implemented as follows:
```java
@Override
public String toString() {
    return SimpleUnitFormat.getInstance().format(this);
}
```

`SimpleUnitFormat` knows the `MetricPrefix`es and has internal arrays of the metric prefix symbols and converters (`String[] PREFIX_SYMBOLS` in `SimpleUnitFormat:110`, `UnitConverter[] PREFIX_CONVERTERS` in `SimpleUnitFormat:116`).

However, `SimpleUnitFormat` has no knowledge of the `BinaryPrefix`es, so it does not know how to format the given `TransformedUnit` and formats it as `[byte?]`.

This happens here:
In `SimpleUnitFormat.nameFor(Unit)` at `SimpleUnitFormat:389` no prefix can be found for the binary prefix:
```java
String prefix = prefixFor(cvtr); // prefix will be null for kibibyte
```
and then ultimatively in `SimpleUnitFormat:422` `[byte?]` is returned:
```java
return "[" + baseUnit + "?]";
```

Finally, as `[byte?]` is not a valid unit identifier, the `IllegalArgumentException` is thrown.

----

**As a side note:**
That whole algorithm of formatting prefixes seems a little weird to me.

Current implementation: The `PREFIX_CONVERTERS` are stored in an array and if a `TransformedUnit` has the same converter as a prefix converter, the corresponding prefix symbol is added to the string.

Wouldn't it be better to give `PowerOfIntConverter` an additional field that stores the prefix, so it knows itself which prefix it has? I think the unit should know if it has a prefix and which prefix.
The prefix of a unit could even be exposed on the public API. Being able to determine the prefix of a given unit is always handy. For example, when formatting the unit. There would be no need for the `PREFIX_SYMBOLS` and `PREFIX_CONVERTERS` arrays and the `SimpleUnitFormat` could handle all types of custom prefixes out of the box.

Sure, kilogram would need special treatment but that's always the case.

If there's interest I could try and put together a pull request. Let me know and I will open a new issue.

**Comment by keilw** [comment]
If you get to a PR, please feel free to raise it.

So far `SimpleUnitFormat` clearly stated
>For all SI units, the 20 SI prefixes used to form decimal multiples and sub-multiples of SI units are recognized.

So as of now, `MetricPrefix` is the only implementation. At least `BinaryPrefix` should also be supported in 2.0 since it graduated into the API.
