### ISSUE TITLE
TemporalQuantity and TimeUnitQuantity use Integer to store the value

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#137]
The `TemporalQuantity` class uses `Integer` to store the value of the temporal quantity. If you pass a `Quuantity<Time>` object to the `of` method, the quantity is converted to seconds. As a result, the following line of code:

    System.out.println(TemporalQuantity.of(Quantities.getQuantity(42, MetricPrefix.MILLI(Units.SECOND))));

will produce the following result:

    Temporal unit:Seconds value: 0

Was there a special reason why `Integer` was used for `TemporalQuantity`, or can/should/must it be changed to `Double`? Or should it even be `BigDecimal`?

**Comment by keilw** [comment]
The whole Temporal types in java.time.temporal only use Integer or maybe Long, that is why a similar data type is used here.

**Comment by filipvanlaenen** [comment]
I checked it out, and `TemporalAmount` and `TimeUnit` both use `long`. Maybe we should at least change to `long`? This would lead to a change in the API though, e.g. the constructor method `of` has an `Integer` parameter, and the return value of `getValue` is also `Integer`.

**Comment by keilw** [comment]
Let's add `of() `with a `long/Long`.  The Integer version can remain (if you pass it there is no loss auto-boxing it to a long). The overriden `getValue()` should return `Long` then, that is the only major change that may also affect unit tests etc.
