### ISSUE TITLE
Parsing fails for SI derived units when using SimpleUnitFormat

### ISSUE THREAD

**Issue by aironm** [unitsofmeasurement/indriya#141]
Hello,

I am using using 1.2 version of indriya. The below statement fails with parse error.

`SimpleUnitFormat.getInstance(SimpleUnitFormat.Flavor.ASCII).parse("m3");`

Am I missing something here?

Needs #114

**Comment by filipvanlaenen** [comment]
Not sure whether `"m3"` is supposed to work, but the following will work fine:

    SimpleUnitFormat.getInstance(SimpleUnitFormat.Flavor.ASCII).parse("m^3")

**Comment by keilw** [comment]
@filipvanlaenen Thanks, that should be the correct way to parse it here unless you defined any kind of label or alias "m3". I leave it to confirm, but either of you are welcome to close if the solution is fine.

**Comment by desruisseaux** [comment]
Note sure if this is relevant to the discussion, but just as a comparison point, Seshat parses units like "m3".

**Comment by keilw** [comment]
I believe in UCUM it also must work according to the spec, but unlike Seshat the systems using Indriya are not as closely related, e.g. because the `UnitRegistry` concept combines UCUM, SI and other systems it seems legitimate there. Until some of these concepts made it into the API, I don't think all implementations have to do this the same way.

**Comment by keilw** [comment]
@aironm did you try the same with the `UCUMFormat`? Based on the spec it should work there.

**Comment by aironm** [comment]
@keilw : I was not able find UCUMFormat in version 1.2

@filipvanlaenen: I checked in the [code](https://github.com/unitsofmeasurement/indriya/blob/b522823e629f24bfdf0fb343bde7c07fb9addf42/src/main/java/tech/units/indriya/format/SimpleUnitFormat.java#L970) of SimpleUnitFormat where the ASCII flavor adds `m3`, thats why I though that it should work.

**Comment by keilw** [comment]
@aironm That's indeed a little strange. It may be overridden by something.

UCUMFormat is not in the RI, but https://github.com/unitsofmeasurement/uom-systems in the systems-ucum module (note, the 0.9 version is still based on Indriya 1.0, we plan to switch to either 1.2 or even 2.0-EDR in the 1.0 relase of the system and SI modules)

**Comment by keilw** [comment]
I checked the debugger and there may be an issue, that `unitForName()` is called in `getSingleUnit()` but not in `getProductUnit()` which is why the correct equation works fine, but the alias/label doesn't.

**Comment by keilw** [comment]
Actually `getSingleUnit()` is called as part of `getProductUnit()` but "m3" is dissected into "m" and "3". There should be some way to look up the entire string first, if someone has a good idea and wants to look into it, please give it a shot.

**Comment by keilw** [comment]
Test if it's still relevant otherwise we may simply close it.

**Comment by keilw** [comment]
Since there's been no update for almost a year, will close this now,

**Comment by keilw** [comment]
Works for `SimpleUnitFormat` thanks to `alias()`.
