### ISSUE TITLE
"symbol" fields hiding each other

### ISSUE THREAD

**Issue by DrDaleks** [unitsofmeasurement/indriya#145]
`AbstractUnit` has one (fair enough), but
- `BaseUnit` has one
- `TransformedUnit` has one
- `AlternateUnit` has one
- `ProductUnit` has one
This causes quite some havoc. Any reason why this is? Could AbstractUnit.symbol just be protected (full stop)?

**Comment by keilw** [comment]
Most importantly some classes like `BaseUnit` MUST have a symbol, most others only do under special circumstances. Therefore the symbol becomes immutable for particular classes like `BaseUnit`. This I think can't and shouldn't be changed. And we cannot have a protected attribute that is immutable in some subclasses and isn't in others. For some of them they may use the parent value as protected, as long as immutability and final does not matter.

**Comment by keilw** [comment]
There are cases where getSymbol() needs to be overridden, but for the other subclasses it seemed reasonable to use the value in AbstractUnit only. Thanks.

**Comment by DrDaleks** [comment]
isn't immutability sufficiently well handled by just providing (resp. protecting) access to `setSymbol(String)`? Which btw seems overly restrictive as it is currently (might open a new issue+PR).

Btw, why does AlternateUnit still has its own symbol after your latest commit? something I missed in its workings?

**Comment by keilw** [comment]
On the outside yes, in most cases it still would be better to have a `final `member attribute. Several concrete classes have an overriden `getSymbol()` e.g. from the parent unit, but there should not be a member variable outside the `AbstractUnit `class now.

**Comment by DrDaleks** [comment]
I agree, hence my surprise to see that `AlternateUnit` still has a (final) symbol field of its own (at least im master)
