### ISSUE TITLE
Move Contribution Guide to API

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#151]
The Contribution Guide could make more sense in unit-api, and where necessary (e.g. README or top level Indriya Wiki page) it could cross-reference. API, RI and TCK require JCP membership, the others are different. WDYT?

Unfortunately at this point Github does not offer an organization-wide Wiki.

**Comment by Daniel-Dos** [comment]
too think what have more sense in API .

**Comment by Daniel-Dos** [comment]
Hi,

I've created the guide -> https://github.com/unitsofmeasurement/unit-api/wiki/Contribution-Guide.

I'll remove it from Indrya

**Comment by keilw** [comment]
Thanks, I assigned it to you. If you removed it, don't forget to change the link, then maybe with a minor adjustment of the URL we could also merge https://github.com/unitsofmeasurement/unit-api/pull/135

**Comment by Daniel-Dos** [comment]
done. 

I will close this issue.
