### ISSUE TITLE
Unit equivalence Wiki?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#152]
@andi-huber You created a Wiki page for Unit equivalence here, do you feel, it mostly belongs to the RI or could it also move to the API wiki alongside other discussions like https://github.com/unitsofmeasurement/unit-api/wiki/Arithmetic-operations-on-Quantity? 
That page talks about Quantity equivalence, so the two seem related.

**Comment by keilw** [comment]
Actually forget about it, some paragraphs like https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence#implementing-a-normal-form are very implementation-specific, so while it seems a good idea to do some cross-referencing, this belongs here.

**Comment by andi-huber** [comment]
Hi Werner, the Normal-Form with its 7 concrete converters as described on the wiki page is specific to the RI, but first 3 chapters `Quick Facts`, `The 'Word Problem'` and `Decide-ability of 'Equivalence'` are considered more generally applicable. These could be copied over to the API wiki.
