### ISSUE TITLE
CompoundUnit or CompoundQuantity?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#17]
Hi,

I did a bit of brush-up to Indriya over the holidays. And through JUnit tests for `CompoundUnit` a problem occurred to me we should rethink the need for a `CompoundUnit` as opposed to something like a `CompoundQuantity`. 

It is currently possible to create a compound chained across even multiple steps like `HOUR.compound(MINUTE).compound(SECOND)`. However, trying to combine this type of `Unit` into the current `Quantity`, how to handle `"1 hour: 5 minutes: 30 seconds"`, if only the unit part is multidimensional? We may need something along the lines of a `CompoundQuantity`.  JSR 310 `TemporalAmount` could be a very vague inspiration, but we should ask ourselves questions like do we need a `List` or `Set` of units, because `TemporalAmount` states
> The list of units completely and uniquely represents the state of the object without omissions, overlaps or `duplication` 

Which would speak for a Set avoiding duplication.

Either way, it seems we have to think about that and come up with an idea how to best combine a "list" of Unit elements and numeric values attached. JSR 310 `TemporalAmount` implementations are overly simplified, they do not allow more than 2 or 3 distinct units each. E.g. "Year, month, day" in case of the `Period`. We need a more flexible approach for general purpose unit support.

**Comment by keilw** [comment]
I created an approach to a [CompoundQuantity](https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tec/units/indriya/quantity/CompoundQuantity.java) Please have a look and comment here or **VOTE** using the GitHub "Like" function.

If there is a benefit in keeping **CompoundUnit** especially for formatting, the two may co-exist and e.g. a `CompoundQuantity` may be created by passing a `CompoundUnit` and a collection of numeric values. `CompoundQuantity` is backed by a `LinkedHashMap` to preserve the order, e.g. `6ft 3in` rather than a mix-up. If `CompoundUnit` was able to return its units in a similar way, then the two classes may co-exist in a synergetic way. If we want to extend `Quantity` formatting to `CompoundQuantity`, it may require an API interface (somewhat similar to `TemporalAmount` in the JDK) otherwise it may not be required in the API, that's up for discussion. Since the state and value of a `CompoundQuantity` cannot be retrieved without conversion like the to() method (if this should be called differently for a `CompoundQuantity` please advise, it was just a first draft) it seems to make no sense to implement or inherit the `Quantity` interface IMO.

**Comment by desruisseaux** [comment]
I can conceive `CompoundQuantity` as a generalization of `TemporalAmount`, but do we have a use case for it (other than temporal)? Compound quantities like _"2 feet and 6 inches"_ is the same quantity than _"2.5 feet"_. Displaying such value as _"2 feet and 6 inches"_  can be considered as `QuantityFormat` work. This is different for `TemporalAmount` because of the complication of calendars (leap seconds, _etc._). But I'm not aware of any such ambiguities for length measurements for example?

**Comment by keilw** [comment]
We did have to model these in the container business with sizes like [Container Dimensions](https://westerncontainersales.com/wp-content/uploads/2015/09/Container-Dimensions1.jpg) I managed to overcome it in 363 by doing something along the lines of `Quantities.getQuantity(8, FOOT).add(Quantities.getQuantity(6, INCH)`. It works and if we wanted to improve quantity formatting with certain patterns like `ft in` (JSR 310 also does offer all sorts of things, JodaTime offers even a bit more) we could also do that. We are in a story-defining phase, if you want please create another issue/story for unit/quantity formatting.

**Comment by desruisseaux** [comment]
I think we can handle that with formatter only. For example when formatting 48.5 as an angle like 48°30′00″, I can use an `AngleFormat` class and set its pattern to "DD°MM′SS″" where DD stands for degrees, MM stands for minutes and SS stands for seconds (similar approach than patterns in date format).

Wouldn't it be safer to restrict units to non-compound quantities? Otherwise it would introduce a complexity in calculation or unit conversions which is not necessary if we can address the same needs with formatter.

**Comment by keilw** [comment]
`AngleFormat` (in SIS I assume) could be a good inspiration, [CompoundUnit](https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tec/units/indriya/unit/CompoundUnit.java) also mentions `DD°MM′SS″` as another example for a compound unit. The class that serves as a discussion base (also deprecated it like `CompoundUnit` as it may change or even go away later) is not meant to be directly converted or calculated on for that reason. Only results of methods like `get()` or `to()`.

**Comment by keilw** [comment]
**The following 3 options are up for discussion:**
Please vote (if you want also for multiple, please not for all of them if possible;-) using the +"Like" button here.

**Comment by keilw** [comment]
A) Model https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tec/units/indriya/quantity/CompoundQuantity.java and if required CompoundUnit in a similar way as e.g. TemporalAmound in JSR 310

**Comment by keilw** [comment]
B) Model `QuantityFormat`

**Comment by keilw** [comment]
C)

**Comment by duckAsteroid** [comment]
Maybe I missed the point (tell me if I have): would the idea of preserving a qty like `6 ft 4 inches` as a compound facilitate better maths? e.g. `6ft 4in` + `6ft 2in` = `12ft 6in` (or `12.5 ft`)

Since the alternative of `6ft 4in` is `6.3333333333333 ft` starts to feed precision errors when we do maths operations?

**Comment by keilw** [comment]
Thanks for voting and the input. Those are valid questions and challenges we should answer together. @desruisseaux mentioned that Apache SIS mainly for quantities like `Angle`. Therefore in a broader context maybe formatting alone is not enough...?

**Comment by desruisseaux** [comment]
Hello Chris

Le 15/01/2018 à 11:56, Chris Senior a écrit :

> Maybe I missed the point (tell me if I have): would the idea of
> preserving a qty like |6 ft 4 inches| as a compound facilitate better
> maths? e.g. |6ft 4in| + |6ft 2in| = |12ft 6in| (or |12.5 ft|) Since
> the alternative of |6ft 4in| is |6.3333333333333 ft| starts to feed
> precision errors when we do maths operations?
>
It is indeed one way to avoid floating point inaccuracy. But an
alternative could also be to express "6 ft 4 inches" as "76 inches", and
let QuantityFormat decompose "76 inches" as "6 ft 4 inches" at
formatting time.

    Martin

**Comment by keilw** [comment]
Martin/Chris, 
Thanks for raising those points and discussing possible solutions to issues like the loss of precision. That is very similar to e.g. what JSR 354 and other Monetary libraries face when it comes to monetary amounts. Some frameworks and financial apps therefore store the amounts as the smallest fraction, e.g. `250 cent` for `2€ 50cent`. This could be an approach here.

**Comment by ejberry** [comment]
@desruisseaux and @keilw,
Decomposing to the smallest unit is a fine approach if all units are of the same system, but if not we'll still get the same floating point inaccuracies. While this is an edge case, there are a handful of countries that use odd mixes of metric and imperial system where this could pop up.

**Comment by keilw** [comment]
@ejberry  Thanks for the input. Everyone who is contributor or EG member is more than welcome to fork Indriya and propose a PR around this or other challenges. Should get the QuantityFormat into the API soon, then what's already refactored as [AbstractQuantityFormat](https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tec/units/indriya/format/AbstractQuantityFormat.java)

**Comment by jhg023** [comment]
To clarify, let's assume the following two cases:
- 6 ft. 4 in. (76 in.)
- 6 ft. 4 ft.

The first case has two quantities of different units while the second case has two quantities of the same unit.

I wouldn't mind designing a solution for fomatting compounded quantities, but would it be better if there were two different formats for quantities with varying units (quantities with the same unit would be decomposed to the smallest unit)?

**Comment by keilw** [comment]
Thanks for the input. The draft of a `CompoundQuantity` does not allow duplication of the same unit. JSR 310 does, although its JavaDoc speaks of unique without duplication, but there in theory the List of `TemporalUnit` entries may contain the same unit twice. So far in this case a `Set` was used. 
At the moment if you add `6 ft`. and `4 ft`. the resulting `Quantity` is `10 ft`. And even without a dedicated `QuantityFormat` API element existing implementations would properly format that.
However adding `6 ft`. and `76 in`. right now this Quantity will end up as FEET because it was the first element in the operation. Unless you did `6ft.to(INCH)` first, or reversed the addition by adding `6 ft`. to `76 in`. So even without a dedicated `CompoundQuantity` (right now there is a decent majority for C) we would have to ensure `Quantity` implementations can somehow keep track of all the operations that were applied before getting to a new `Quantity` and which one e.g. is the `smallest` of these.

**Comment by jhg023** [comment]
I see.  Assuming we stick with the current draft of `CompoundQuantity`, would it be possible to utilize `ComparableQuantity` (or just `ComparableUnit`) to allow for the use of a `TreeMap<ComparableUnit<Q>, Quantity<Q>>` to allow for sorting by unit?  I'm not sure if something like this would be feasible, as I'm still trying to wrap my head around the design and what can (and cannot) be changed at this point.  For something like that to work, I reckon the following would have to be added to `ComparableQuantity`:
```java
@Override
ComparableUnit<Q> getUnit();
```

**Comment by keilw** [comment]
This draft is part of either option A) or B). And even if the list was reconciled with just 2, the current option C) has the most votes. If we go for that, there would be neither `CompoundUnit` nor `CompoundQuantity`.

**Comment by jhg023** [comment]
Understandable.  Assuming option C) maintains the most votes, do we have an idea of how the implementations of `QuantityFormat` (I believe this has been renamed to `AbstractQuantityFormat`) will format compound quantities?  If it's just going to be a utility method that accepts a variable amount of `Quantity<Q>` or `ComparableQuantity<Q>`, then I could create drafts for each implementation.

**Comment by keilw** [comment]
Yes, QuantityFormat is in the API now, just resolving https://github.com/unitsofmeasurement/indriya/issues/23 to implement that here. I am not sure, if there's enough evidence on how to do it without modelling the compound values, but e.g. @desruisseaux said they did something like it in SIS with [AngleFormat](https://sis.apache.org/apidocs/org/apache/sis/measure/AngleFormat.html) That is just a single quantity, so hard to say if the approach would be versatile enough, but have a look at it if you can.

**Comment by filipvanlaenen** [comment]
Would there be cases where one wants to handle something like ``1m 3ft``? And would you in that case also want ``1m 3ft + 2m 4ft = 3m 7ft``?

**Comment by keilw** [comment]
I am not sure, if operations like `add()` properly work for a `CompoundQuantity `like it does for `Quantity `(aka implementing `Quantity`) but I'd be open to that. If so, then the addition would indeed have to loop over each set and add exact matches into a new `CompoundQuantity`.

**Comment by keilw** [comment]
The problem is, that of `Quantity` at least `getUnit `and `getValue `don't make sense, but instead **plurals** like `getUnits `or (not there, but it might also exist) `getValue `are needed.

**Comment by keilw** [comment]
There have been several branches in uom-se, so after merging https://github.com/unitsofmeasurement/indriya/pull/47, let's create two branches, one for option A which is fully functional (the support by QuantityFormat still could be improved, but it works like JSR 275/JScience did) already. Another one for Option C something like "quantityformat_only" or similar. All relevant classes will be removed from the master branch till either of them produce a satisfactory approach that can be merged back.

**Comment by keilw** [comment]
@andi-huber Thanks for the update and checking out the options. I am not entirely sure if a `CompoundUnit` is necessary but experience, maybe also mistakes by JSR 310 added the necessity of the `TemporalAmount `(which is more like a `CompoundQuantity` or `QuantityAmount` if you want) Except for certain aspects of rendering, the `CompoundUnit` likely adds less value than being able to exactly assign how many feet, inch or metre you want in a particular compound value.

**Comment by keilw** [comment]
P.s.: For Indriya I added individual write access for @andi-huber and @filipvanlaenen (only EG members normally have) so it's easier to work on these feature branches. Please use it with care and coordinate any push to master first or do a PR, but for the feature-branch it's fine to work there directly instead of your own local forks.

**Comment by andi-huber** [comment]
I started work on the 'Unit equivalence problem', that is to decide whether 2 compositions of UnitConverters are equivalent. 

The only way I see to solve this, is to have unit composition mechanics produce a so called 'normal-form', which involves reordering, simplification and canceling out of UnitConverters within a sequence of UnitConverters that constitute the composed converter transformation.

eg `add(3) ○ add(-3)` should cancel out to the identity transformation

Here's my conclusion:
I believe doing Unit composition with proposed 'compounds' (Option A) can get very complicated, there is a lot of undefined behavior regarding composition of 'formats'.
In contrast providing a solution that just uses formatters (Option C) that get applied at the end of an arbitrary complex quantity computation, seems way easier to implement. Also this is straight forward from a user's perspective, (s)he would not have to consult java-doc for every composition step they want to make.

I'm voting C)

**Comment by andi-huber** [comment]
... I also believe, that all 'compound ideas' could be translated and reused eg for a 'compound format builder'

**Comment by keilw** [comment]
Thanks for voting and your thoughts on the matter. Would you be able to start something in the "format-only" branch?

I got some pretty good results to format a `CompoundQuantity` in the other branch while `CompoundUnit` seems of very little use. However **parsing** is the real tricky beast in both cases.
E.g. if the concept of a "Compound.." something is completely abandoned, then the only option for `QuantityFormat` is to parse the result of say `5ft 10in` or `2mi, 10km, 50mm` back into a single `Quantity`.

**Comment by andi-huber** [comment]
Is it possible to translate existing
```
ONE_HPA = Quantities.getQuantity(BigDecimal.ONE, HECTO(PASCAL));
TEN_PA = Quantities.getQuantity(BigDecimal.TEN, PASCAL);

pressures = new CompoundQuantity<>(ONE_HPA, TEN_PA);
assertEquals("1 hPa 10 Pa", pressures.toString());
```
into something like ...
```
ONE_HPA = Quantities.getQuantity(BigDecimal.ONE, HECTO(PASCAL));
TEN_PA = Quantities.getQuantity(BigDecimal.TEN, PASCAL);

formatter = CompoundFormat.of(HECTO(PASCAL), PASCAL);
sum = ONE_HPA.add(TEN_PA);

assertEquals("1 hPa 10 Pa", formatter.format(sum));
```

**Comment by keilw** [comment]
If a specialized `QuantityFormat` (CompoundQuantity is currently not an API element and it may be fine to stay in the RI or its own SPI like we did with `Range` or `Measurement`) had to store `Quantity` information then what complexity would that safe?

**Comment by andi-huber** [comment]
As suggested above, the 'formatter' would store Unit information, not Quantity information.

**Comment by keilw** [comment]
Ok then it's closer to @dautelle's option B whether you call it `CompoundUnit` or not (if we find the construct helpful, why not explore that as well) So please check out https://github.com/unitsofmeasurement/indriya/tree/compound_format_only and propose something there.
