### ISSUE TITLE
What's the purpose of BaseUnit#quantityType?

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#179]
The class `BaseUnit` has an attribute `quantityType` that can be set through one of the constructors.

However, I can't see that the attribute is used anywhere, and what purpose it would have.

Can it be removed?

**Comment by keilw** [comment]
It was an idea about preserving the quantity type at runtime, but it cannot be assigned in Java at the moment, so I think we can remove it till the Java platform could ever add reified generics?
