### ISSUE TITLE
Loss of Precision due to long/double conversion

### ISSUE THREAD

**Issue by kfp** [unitsofmeasurement/indriya#182]
The following fails seemingly due to loss of precision over the RationalConverters switching between long/doubles. 

    val value = new Long(1548351392775L);
    val mili = NumberQuantity.of(value, MetricPrefix.MILLI(SECOND));
    val nanoLong = mili.to(MetricPrefix.NANO(SECOND)).getValue().longValue();
    assertEquals(value * 1000000, nanoLong);

Is there a different pattern which should be followed for big longs?

**Comment by keilw** [comment]
As seen in this [demo](https://github.com/unitsofmeasurement/uom-demos/blob/master/console/java10/src/main/java/tech/uom/demo/PrecisionDemo.java) for Java 10 (the example seems Kotlin) it works if you explicitly use `BigInteger`.
