### ISSUE TITLE
Why Unit's getName() and getSymbol() are returning null ?

### ISSUE THREAD

**Issue by cvgaviao** [unitsofmeasurement/indriya#190]
While experimenting with /uom-console-demos-java10/src/main/java/tech/uom/demo/spi/SystemsDemo.java I noted that many of the units listed are returning null for getName() and getSymbol() methods;
Also interesting is that their toString() are returning their symbol properly.
```Reporting Units
1; null; A; A
2; null; null; ℃
3; null; lm; lm
4; null; ; one
5; null; C; C
6; null; Sv; Sv
7; null; F; F
8; null; H; H
9; null; J; J
10; null; null; m²
11; null; K; K
12; null; mol; mol
13; null; lx; lx
14; null; N; N
15; null; Pa; Pa
16; null; Gy; Gy
17; null; S; S
18; null; rad; rad
19; null; T; T
20; null; V; V
21; null; W; W
22; null; d; day
23; null; null; week
24; null; null; m/s
25; null; null; km/h
26; null; kg; kg
27; null; sr; sr
28; null; kat; kat
29; null; cd; cd
30; null; h; h
31; null; null; %
32; null; null; year
33; null; Ω; Ω
34; null; Wb; Wb
35; null; null; ㎥
36; null; null; g
37; null; m; m
38; Litre; null; l
39; null; Bq; Bq
40; null; Hz; Hz
41; null; s; s
42; null; min; min
43; null; null; m/s²
``` 

Wouldn't they at least have a default English name ?

Btw, which road would be better to deal with i18n ?

**Comment by cvgaviao** [comment]
Btw, I changed the version of dependencies to "2.0-EDR"

**Comment by keilw** [comment]
Hi, it's supposed to be like that, only `BaseUnit` and a few others are meant to return a symbol, while others especially `TransformedUnit` have none. `Unit.getSystemUnit()` should return a Unit that also has a symbol. The name is "nice to have" but except for base units it is also not set in a lot of cases. As you mentioned, the name is also dependent on a locale, and `LocalUnitFormat` is not the default formatter, but please have a look at it and you're welcome to contribute further improvements if you are interested to help in this area.

**Comment by cvgaviao** [comment]
Ok, but I'm wondering... I've planned do looking at it more carefully soon, but maybe you can help figure out...

Suppose I have a webservice which are receiving an order (json) containing two attributes: quantity and measure-unit code. 
How am I supposed to obtain an instance of a specific Unit to deal with this item without a representational string for it? search by the symbol ?

I don't see how, unless I start to save the symbol in the database, but that would require database to support utf-8 I'm guessing.

**Comment by keilw** [comment]
Each unit has a unique key, but that's the string representation. **JSON** parsing is done with libraries like https://github.com/unitsofmeasurement/uom-lib/tree/master/jackson already.
