### ISSUE TITLE
FormatCompound test failure: confusion between comma and dot characters

### ISSUE THREAD

**Issue by thodorisbais** [unitsofmeasurement/indriya#192]
I know #187 is still in progress and I haven't checked the underlying code of the test, but given that the current HEAD builds successfully, I suspect this is a local formatting issue we need to investigate:

![screenshot 2019-02-23 at 23 51 01](https://user-images.githubusercontent.com/5684688/53292724-262cca80-37c7-11e9-8d3d-49c459c3fd1b.png)

I am on a Mac, but it's weird that it passes on the remote build (, which is also unix).

**Comment by keilw** [comment]
Try now, I guess that should fix it. I use a PC I bought in the US, thus the `Locale` is usually English. I set it explicitly now, that should work. You probably got a Dutch locale when running it.
