### ISSUE TITLE
Provide a descriptive name or similar method for UnitFormat

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#193]
Currently `SystemOfUnits` has a descriptive name and `getName()` method.  Although registered under a key and possible aliases (currently this is implementation-specific, using the getter in the SPI interface) the `UnitFormat` implementation class only has a class name. Which may not always be a nice, human-readable string. Overriding `toString()` can help, so this could be sufficient, but let's discuss the question of a descriptive string when new versions of the API arise.

**Comment by thodorisbais** [comment]
Closed with 5b280045b3915de90da3075d12871c5d7f3ac31d
