### ISSUE TITLE
Could we use a "fluent" Builder for NumberDelimiterQuantityFormat?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#194]
While `SimpleQuantityFormat` is controlled by a pattern only, creating `NumberDelimiterQuantityFormat` uses multiple arguments. Could we either use the separate class `NumberDelimiterQuantityFormatBuilder` (currently `deprecated`) or an inner class like `NumberDelimiterQuantityFormat.Builder` (similar to `Calendar.Builder` or `Locale.Builder`) to fluently create new instances of the format?

**Comment by thodorisbais** [comment]
Closed with #195 , 2b25abc2db448ef9a63d72f4b4235df8dd507bc2 and 04a5db30053d9de400f759d39cc42a331bd74ee6.

**Comment by keilw** [comment]
Thanks @thodorisbais I would however reconsider the `withXYZ()` method names based on both the JDK builders in `Calendar` or `Locale`. And the other JSR I lead alongside @otaviojava and @atsticks also has builder methods like `setCurrencyCodes()` in classes like `CurrencyQueryBuilder`, so I would like to stay consistent both with the JDK and other JSRs we take care of. I can fix this unless someone was faster with a PR.

**Comment by thodorisbais** [comment]
Cool, good to know that it's also like that in the rest of JSRs. No worries, I'll take care of it in a tad.
