### ISSUE TITLE
Remove Waffle

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#196]
Waffle is closing down. While a few aspects like dependencies between issues do not seem covered by GitHub tracker itself, the Kanban board is now available on an organization level with GitHub Projects, thus we do not really need Waffle any more.
All badges will be removed as soon as possible.

**Comment by Daniel-Dos** [comment]
Hi @keilw 

explain me this problem

would it only remove the link to Wafle in the README?

**Comment by keilw** [comment]
Yes, I will do what's necessary when it comes to closing the actual Waffle account, so this and other issues is mainly to avoid broken links, just when java.net went away ;-)

**Comment by Daniel-Dos** [comment]
OK,

I'll send a PR to remove the link.

thank you

**Comment by Daniel-Dos** [comment]
closing this issue .
