### ISSUE TITLE
Allow tweaking of AbstractUnit.toString()

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#2]
Right now the string representation of any `Unit` based on `AbstractUnit` uses `SimpleUnitFormat` in its default variant.
There was an attempt to make this dynamically use the current `UnitFormat` of the current `ServiceProvider`, but it had unpredictable and unwanted side-effects that could lead to initialization of AbstractUnit being prevented. Since a chain of different modules may have a similar effect, it is not too likely to work here in the future either (if you feel you have a working, stable answer, please propose it) 

However, it should be possible to offer a simple and easy tweak, e.g. via System properties to select e.g. between:
- SimpleUnitFormat.DEFAULT (predefined)
- SimpleUnitFormat.ASCII for ASCII characters only
- EBNFUnitFormat
- LocalUnitFormat

All of which are build in.

**Comment by thodorisbais** [comment]
After a very short investigation, it looks like the property's retrieval part is straightforward: something like a switch for the specified property inside the <code>AbstractUnit.toString()</code> .

Where should we be set the property's value, though?
Somewhere like `NumberDelimiterQuantityFormat`'s constructor maybe?

_Maybe that's a very basic question, but I'm wrapping it up for today and had quite little amount of time to take a better look; that is, I'd like to be ready to actually work on it tomorrow and that's why I'm shooting the question now._

**Comment by keilw** [comment]
It's hard to say, but if it could be configured, that would be nice. Trying it earlier led to the mentioned static problems, so I am not sure, if the `ServiceProvider` could be used, but potentially other static factories of `EBNFUnitFormat`, etc. A caveat about `LocalUnitFormat` is, that the default locale would have side-effects that differ depending on that locale, but if it's well-documented, switching and configuring it might be nice. It is nice to have but not an absolute MUST for 2.0.

**Comment by wnreynoldsWork** [comment]
So it sounds like this was implemented - is that the case? Is there a way to select the SimpleUnitFormat that is used to print out units? I would like my units to print out in ASCII.

**Comment by keilw** [comment]
No it doesn't have a milestone, but pure ASCII has been available for some time, all you need is to call `SimpleUnitFormat.getInstance(ASCII)`. the `toString()` implementation is not restricted to ASCII. If we find a way to configure that at least via some properties, that is the goal of this ticket but it is for a future version.

**Comment by wnreynoldsWork** [comment]
Right, that is clear. But if I have a unit METRE.divide(SECOND).pow(2).toString(), I get the UTF format

m/s'\u00b2' . I would like m/s^2.  AbstractUnit.toString() always uses the DEFAULT SimpleUnitFormat instance, which prints out in UTF.  

Is there a simple way to get Quantity.toString() to use the ASCII instance of SimpleUnitFormat? Right now it appears to format units using SimpleUnitFormat.getInstance(), which returns DEFAULT, not ASCII.

**Comment by keilw** [comment]
ASCII is just a flavor of `SimpleUnitFormat`. With Quantity it is even a bit more complex because there is SimpleQuantityFormat also a minimal denominator because there are many possible combinations of `UnitFormat` and `NumberFormat`.

**Comment by keilw** [comment]
Since it would have a side-effect on `AbstractUnit.parse()` which unlike `toString()` is also static let's close this for now. We may revisit it later in this place or another.
