### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#20]
The code coverage is currently **40%**, see codecov badge. We should create more JUnit tests especially in packages with a very low coverage. At least 60% like the JSR 363 RI should be archived, if more, even better.

**Comment by filipvanlaenen** [comment]
The codecov badge says 50% today! :-)

**Comment by thodorisbais** [comment]
Currently at 59%, but it should definitely improve. Maybe a good candidate for our OC1 Hackergarten.

**Comment by keilw** [comment]
Yes, it is not a killer criteria but certainly a low hanging fruit. Could be combined e.g. with increasing the use of Hamcrest where appropriate.
