### ISSUE TITLE
hashcode of dividend twice

### ISSUE THREAD

**Issue by jonaskello** [unitsofmeasurement/indriya#201]
https://github.com/unitsofmeasurement/unit-ri/blob/9e5b2556b41dfc470c3b9bfb6d23d5f74d115485/src/main/java/tec/units/ri/function/RationalConverter.java#L178

In this line, the hash is the sum of `dividend` is added to itself. I think it should be the sum of `dividend` added to `divisor`.

**Comment by keilw** [comment]
Test if it's still relevant, otherwise close it.

**Comment by andi-huber** [comment]
fixed with PR #226
