### ISSUE TITLE
IntegerQuantity's multiply(Number) has surprising and bug-prone behavior

### ISSUE THREAD

**Issue by dlwh** [unitsofmeasurement/indriya#202]
I recently stumbled on some pretty nasty behavior that I think should probably be changed.

What does the following return?

```java
public Quantity<Length> scale(Quantity<Length> q) {
  return q.multiply(Math.sqrt(2));
}
```

Unfortunately, it depends. If you pass in an IntegerQuantity, you end up with exactly the same value you passed in, because IntegerQuantity truncates before multiplying: https://github.com/unitsofmeasurement/unit-ri/blob/master/src/main/java/tec/units/ri/quantity/IntegerQuantity.java#L91

But, Quantities.getQuantity(...) returns the same static type independent of the type of the number you pass in, which makes this behavior very surprising.

This seems very dangerous, especially for a library whose main point is to avoid silent calculation bugs due to unit mismatch...

**Comment by keilw** [comment]
Based on #220 I'm closing this.
