### ISSUE TITLE
Behavior of AbstractUnit.compareTo not sufficiently defined

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#204]
The Javadoc for the `AbstractUnit.compareTo` is unclear about what the expected behavior should be when the name of the other unit is smaller, but the symbol larger.

What I would expect is that e.g. symbol takes precedence of name. I.e. is the symbol smaller, than the unit is smaller. Are the symbols equal, than the unit is smaller if the name is smaller. If symbol and name are equal, than the unit is equal.

If the description above is the expected behavior, we should implement that and describe it in the Javadoc.

**Comment by keilw** [comment]
Thanks, that's a good point. Unlike `equals()` or `hashCode() compareTo()` is not overridden in most of the concrete `Unit` types, therefore some of them with special attributes like `parentUnit` or `units` (in case of a `MixedUnit`) may have to be taken into consideration as well.

**Comment by andi-huber** [comment]
Just a thought: instead of hard-wiring the logic, why not have a non static field somewhere, to put a `Comparator<Unit>`, which we then use throughout the RI.

This would allow users to provide their own. That said, we might also pre-define some for convenience:

- CompareBySymbol
- CompareByName (my suggested default)
- CompareBySymbolThenName

**Comment by solr00t** [comment]
Implementing Comparable doesn't seem meaningful for a unit of measurement, and I'm having a hard time imagining a use case where I'd need to do this. In the rare case that a user wants to compare or sort units by their names or symbols, it would be pretty trivial for them to write their own Comparator.

**Comment by andi-huber** [comment]
Agreed, still we need to provide an implementation for `Unit.compareTo(Unit)`. I'm suggesting to keep it flexible, just in case.

**Comment by keilw** [comment]
This is over one year since the last comment, is there something to do or can it be closed?

**Comment by keilw** [comment]
The JavaDoc already states that the method gives precedence to the **symbol**.

**Comment by keilw** [comment]
@andi-huber, @filipvanlaenen Is there something you could imagine doing about this one before 2.1.3 which is supposed to go out either this quarter or at most in Q3?
