### ISSUE TITLE
Behavior of AbstractUnit.isCompatible deviates from Spec

### ISSUE THREAD

**Issue by andi-huber** [unitsofmeasurement/indriya#210]
Javadoc from `javax.measure.Dimension`

> Two units u1 and u2 are compatible if and only if u1.getDimension().equals(u2.getDimension()). 

This seems to be implemented incorrectly ...

Suggested improvement: re-implement `QuantityDimension.equals` such that `AbstractUnit.internalIsCompatible` can return `thisDimension.equals(thatDimension)` ...

```java
  private final boolean internalIsCompatible(Unit<?> that, boolean checkEquals) {
    if (checkEquals) {
      if (this == that || this.equals(that))
        return true;
    } else {
      if (this == that)
        return true;
    }
    if (!(that instanceof AbstractUnit))
      return false;
    Dimension thisDimension = this.getDimension();
    Dimension thatDimension = that.getDimension();

    // suggested change ...
    return thisDimension.equals(thatDimension);

//    currently ...
//    if (thisDimension.equals(thatDimension))
//      return true;
//    DimensionalModel model = DimensionalModel.current(); // Use
//    return model.getFundamentalDimension(thisDimension).equals(model.getFundamentalDimension(thatDimension));
  }
```

**Comment by keilw** [comment]
The `DimensionalModel` was introduced with JScience5, the draft of which inspired large portions of the RI. It is rarely used, I think this code fragment is the only actual use case. @dautelle Could you tell us a bit more about the idea behind it. And does it make sense here or could the change @andi-huber suggested allow to deprecate it and ultimately eliminate from the SPI?
If not, we should at least brush the concept of "Dimensional Model" and http://en.wikipedia.org/wiki/Dimensional_analysis in the spec.

**Comment by keilw** [comment]
@dautelle, @andi-huber What do you suggest here? Should we mention "Dimensional Analysis" in the Spec or remove `DimensionalModel` from the RI instead? (or mark it as Deprecated and not use it in above code) It's not a big issue, but I would like to have it done with 2.0

**Comment by keilw** [comment]
The JavaDoc in AbstractQuantity already mentions the "fundamental dimension" and the Spec now also does.
