### ISSUE TITLE
Add support for higher precision to selected Unit operations

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#222]
After the API got additional (overriden) `Unit` operations by https://github.com/unitsofmeasurement/unit-api/issues/191 they should be used where applicable in the RI.

The default behavior for each in `AbstractUnit` is to use `Number.doubleValue()`, where higher precision is desired, the operations should be overridden in a particular concrete `Unit` implementation.

**Comment by keilw** [comment]
I believe this is mostly done through the new `MultiplyConverter `and `RationalNumber`. @andi-huber any thoughts or something that might be missing?

**Comment by andi-huber** [comment]
Higher precision arithmetic is now applied to all arithmetic operations in `AbstractUnit`. Effectively the `Number` arithmetic associated with `add/multiply/divide/...` is delegated to the configured `NumberSystem` (SPI). At least that's the desired behavior.

**Comment by keilw** [comment]
Ok thank you, so closing it.
