### ISSUE TITLE
NumberQuantity operations can cause very large results

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#237]
The new Number Arithmetic breaks a vast majority of JUnit tests in `si-units` (`2.0-SNAPSHOT`)

While some look like an improvement e.g. `1000` instead of `1000.0d`, others are hard to understand or just look wrong e.g.
- [x]  `new BigDecimal("3339.461218000000000000000000000000000000")` in [ArithmeticTest](https://github.com/unitsofmeasurement/si-units/blob/master/units/src/test/java/si/uom/ArithmeticTest.java)
- [x] new `BigDecimal("0.017453292519943295769236907684886129174041179373241439316730392568668")` in [AngleTest](https://github.com/unitsofmeasurement/si-units/blob/master/units/src/test/java/si/uom/AngleTest.java)

The dozens of trailing zeros are totally bizarre, hope there's a way to overcome that?
And 70 decimal places in the second case are too precise for most use cases, we should be able to control it as well but I guess it's second priority.

**Comment by andi-huber** [comment]
Any test that compares numbers for equality should do this by comparing their values also explicitly providing an expected accuracy goal.

**Comment by keilw** [comment]
Seems acceptable for the giant number, either one has to compare with `BigDecimal` or the `doubleValue()` if they accept less precision, but `3339.461218000000000000000000000000000000` is just a a nuisance, can we get rid of that somehow?

**Comment by andi-huber** [comment]
My suggestion is to avoid Indriya's `MultiplyConverter` where ever possible! It seems reasonable to use `RationalConverter` as a drop-in replacement (even if the numbers represented are irrational). 

So in SI.java, instead of 

```java
public static final Unit<Mass> UNIFIED_ATOMIC_MASS = addUnit(
	    new TransformedUnit<Mass>(KILOGRAM, new MultiplyConverter(1.660538782E-27)), "Unified atomic mass", "u",
	    true);
```

use 

```java
private final static RationalNumber KILOGRAM_PER_UNIFIED_ATOMIC_MASS = //1.660538782E-27 
            RationalNumber.of(
                    BigInteger.valueOf(1660538782L), 
                    new BigInteger("1000000000000000000000000000000000000")); 
    
public static final Unit<Mass> UNIFIED_ATOMIC_MASS = addUnit(
	    new TransformedUnit<Mass>(KILOGRAM,
	            new RationalConverter(KILOGRAM_PER_UNIFIED_ATOMIC_MASS)), "Unified atomic mass", "u",
	    true);
```
That should do the trick!

**Comment by andi-huber** [comment]
I'm preparing a PR allowing a shortcut for the above with `RationalNumber.of(double value)`

**Comment by andi-huber** [comment]
PR #241 now allows this

```java
public static final Unit<Mass> UNIFIED_ATOMIC_MASS = addUnit(
    new TransformedUnit<Mass>(KILOGRAM,
	new RationalConverter(RationalNumber.ofDouble(1.660538782E-27))), 
    "Unified atomic mass", "u", true);
```

**Comment by andi-huber** [comment]
... Indriya's `MultiplyConverter` is locked in at double precision, does not support anything else. Hence avoid it where possible.

**Comment by keilw** [comment]
I'll check it out tonight, but why could `MultiplyConverter` not use a `BigDecimal` as factor, too? We added `Number` to a few operations recently.

**Comment by andi-huber** [comment]
I've thought about this too. But that would break our current `NormalForm/Composition Table` in https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence.

We'd need to redesign that. Currently `MultiplyConverter` serves as the fallback for all 'linear' converters. With the `RationalConverter` now extended to also represent Java's double numbers, the `MultiplyConverter` has become almost obsolete.

**Comment by andi-huber** [comment]
... such a redesign could throw the `RationalConverter` away and let instead the `MultiplyConverter` use a Number type instead of a double type for the factor. Where effectively, when the number factor is a `RationalNumber` the `MultiplyConverter` shall act like the current `RationalConverter`.

**Comment by keilw** [comment]
As long as the code and unit tests are not seriously affected or broken, that could be done at some point.

**Comment by keilw** [comment]
Actually would that be possible soon without side-effects? The ballot paving the way for Final has not taken place yet, although both API and RI are ready (there are minor questions but from the EC or wider community nothing came up since our Adopt-a-JSR day) so such small tweaks could also be done before 2.0 goes out.

**Comment by andi-huber** [comment]
I'm already on it, but that's a couple of hours of work. ;)

**Comment by andi-huber** [comment]
Now after PR #242 we can use

```java
public static final Unit<Mass> UNIFIED_ATOMIC_MASS = addUnit(
    new TransformedUnit<Mass>(KILOGRAM, MultiplyConverter.ofDouble(1.660538782E-27)), 
    "Unified atomic mass", "u", true);
```
What ever concrete `MultiplyConverter` is returned here is now an implementation detail of RI.
