### ISSUE TITLE
Make RationalNumber more intuitive

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#238]
A simple addition of `50 kg + 10 lb` now results in assertion errors like
`java.lang.AssertionError: expected:<54.5359237> but was:<545359237÷10000000>`
because the result contains a `RationalNumber` in almost every case.

This is really counter-intuitive, and a burden to use e.g. `doubleValue()` here every time.

See #237

**Comment by andi-huber** [comment]
Any test that compares numbers for equality should do this by comparing their values also explicitly providing an expected accuracy goal.

**Comment by keilw** [comment]
Because of the strange `toString()` representation and other problems (most of them seem resolved now) this was hard for `RationalNumber` with representations like `545359237÷10000000`. This is now only used for `toFractionalString()` similar to e.g. `toScientificString()` in `BigDecimal`. It could be possible to tweak `QuantityFormat` where appropriate to show the fractional representation if desired, but since parsing seems harder (without a dedicated `RationalNumberFormat`)

**Comment by andi-huber** [comment]
I'm basically fine with that. Only thing I'm struggling with is the name in `toFractionalString()` which got me miss-leaded at first glance.

I feel 'fractional' is ambiguous in this case, because it could be interpreted as `non-integer`, which is not what we mean here. I'd suggest to use `toRationalString()` or `toRationalFormat()` instead.

**Comment by keilw** [comment]
Feel free to change it, `toRationalString()` is more consistent, the other name suggests that a `Format` of some kind is returned ;-)

**Comment by keilw** [comment]
It seems the `RationalConverter` needs to remain visible, because at least **UCUM** formatting requires dividend and divisor.

**Comment by andi-huber** [comment]
You might access dividend and divisor from the RationalNumber returned from MultiplyConverter.getScaleFactor(), provided the scale-factor is a rational number.

**Comment by keilw** [comment]
Btw, I fixed that into` getFactor()` simply because it is backward compatible with the 1.0 RI and we must not break everything that was already there ;-) 
Have a look in [UCUMConverterFormatter](https://github.com/unitsofmeasurement/uom-systems/blob/master/ucum/src/main/java/systems/uom/ucum/format/UCUMConverterFormatter.java) but please be extra careful, the parsing and formatting cannot always turn from "." to "/" just because we now use a RationalNumber internally, We have to ensure, that UCUM does not break.
