### ISSUE TITLE
RationalNumber hashcode() and equals() don't work properly

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#239]
Currently comparing two RationalNumber values gives:
`tech.units.indriya.function.RationalNumber<5.002> but was: tech.units.indriya.function.RationalNumber<5.002>`

**Comment by andi-huber** [comment]
With my original draft of `RationalNumber` the `equals` was comparing Java Objects for being the same object (on the heap). This is in line with BigInteger and BigDecimal. This was also explicitly mentioned in the corresponding java-doc.

**Comment by andi-huber** [comment]
... however `BigInteger` is designed differently, so we could take this as the role model:

From `BigInteger.equals()` ... true if and only if the specified Object is a BigInteger whose value is numerically equal to this BigInteger.
