### ISSUE TITLE
Upgrade RI to JUnit 5

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#24]
With JUnit 5 offering many new and advanced features, it seems a good idea to adopt the new version.

**Comment by filipvanlaenen** [comment]
When I run `mvn clean install`, no unit tests are being picked up by Maven. Tried to fix the `maven-surefire-plugin` plugin locally, but without any success. Is there something special I need to do? When I try to run the unit tests in Eclipse, I need to specify explicitly that it should use JUnit 5 as the test runner, even after regenerating the project `mvn eclipse:eclipse`.

**Comment by filipvanlaenen** [comment]
Including `maven-surefire-plugin` directly as a plugin seems to solve the problem. It was only included as a plugin to the website generation. Pull request #46 submitted.
