### ISSUE TITLE
Move AbstractConverter to function

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#243]
I know this is a slightly bigger step, but as a new redefined `MultiplyConverter` interface also got defined (in place of the earlier class) in the function package, and `AbstractUnitFormat` etc. are in the format package, it is consequent here.

**Comment by thodorisbais** [comment]
Closed with 57ea7b85dbc43d9bb7f856df00ad8dc2b5b1da20 , 24a80ee2c87bd5c80bbc2965c3bb0171a0bc9f1a, and 1a138b3977ed7b383e96c265d51ebc77bb5005e4
