### ISSUE TITLE
When doing operations try to prefer PowerOfIntConverter over RationalConverter

### ISSUE THREAD

**Issue by mattdehring** [unitsofmeasurement/indriya#252]
This would fix some of the problems with ending up with different converters depending on how a unit was composed. For example `MICRO(GRAM) != GRAM.divide(1_000_000)`. This would also fix some of the problems with UCUM not being able to determine the correct prefix.

**Comment by keilw** [comment]
They are all created/used as delegates of MultiplyConverter now.

**Comment by andi-huber** [comment]
I took the freedom to revert the proposed changes with PR #255 

Maybe we can workout a different solution to the mentioned issue with `UCUM not being able to determine the correct prefix`. Are there any testcases that showcase this particular problem, so that we can have a closer look at it?

**Comment by mattdehring** [comment]
Here is just one instance in the UCUM test cases where it isn't getting the correct prefix. I agree that that power lookup wasn't a great solution as there are many ways to break it, it just seemed like a simple solution that fixed many common usages. I think isEquivalentTo should be pushed up to the api level if equals isn't going defined to work. 
https://github.com/unitsofmeasurement/uom-systems/blob/44826d36453052c5c393ba928ca47fad41ddb692/ucum/src/test/java/systems/uom/ucum/format/UnitFormatPrefixTest.java#L51

**Comment by andi-huber** [comment]
Thanks for the pointer!
I'm trying to fix this in the `systems.uom.ucum.format.UCUMFormat` class instead.

**Comment by andi-huber** [comment]
This issue is now superseded by https://github.com/unitsofmeasurement/uom-systems/issues/146

I'm closing it.
