### ISSUE TITLE
Add support for GeoTools

### ISSUE THREAD

**Issue by shalomcrown** [unitsofmeasurement/indriya#263]
Trying to use GeoTools with uom-se, I get an exception:
`java.lang.NoSuchMethodError: tec.uom.se.format.SimpleUnitFormat.getInstance()Ltec/uom/se/format/SimpleUnitFormat
`

**Comment by ddcruver** [comment]
GeoTools upgrade from JSR 276 (which was rejected before it was finished) to JSR-363.  

JSR 363 is known as Units 1.0.  JSR-385 is Units 2.0  

Indriya 2.0 is the reference implementation for JSR-385. I don't thnk Indriya 1.0 really exist, I think it started at 2.0 to avoid it being confused as a Unit 1.0 implementation.

**Comment by keilw** [comment]
There is an Indriya 1.x, the most recent version is [1.3](https://github.com/unitsofmeasurement/indriya/releases/tag/1.3).

**Comment by keilw** [comment]
Is there still an action item here?

**Comment by tianhongguo** [comment]
> Trying to use GeoTools with uom-se, I get an exception:
> `java.lang.NoSuchMethodError: tec.uom.se.format.SimpleUnitFormat.getInstance()Ltec/uom/se/format/SimpleUnitFormat `

hello!I had the same problem!Have you solved it？if yes，
Tell me how to solve it！Thanks!

**Comment by keilw** [comment]
You should not use uom-se anymore, If you can't change to Unit-API 2.0 yet although it has been available and Final for over a year, please use [Indriya 1.3](https://search.maven.org/artifact/tech.units/indriya/1.3/bundle), that is the latest JSR 363 implementation.

**Comment by keilw** [comment]
Is this related to #316?
