### ISSUE TITLE
Don't accept non-finite amounts with Quantity constructors

### ISSUE THREAD

**Issue by DrDaleks** [unitsofmeasurement/indriya#285]
Currently using version 2.0.2.

The following line
```Java
Quantities.getQuantity(Double.POSITIVE_INFINITY, Units.METRE).to(MetricPrefix.KILO(Units.METRE));
```

Leads to the following stack trace

```Java
java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:497)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:809)
	at java.math.BigDecimal.valueOf(BigDecimal.java:1277)
	at tech.units.indriya.function.DefaultNumberSystem.multiplyWideAndNarrow(DefaultNumberSystem.java:761)
	at tech.units.indriya.function.DefaultNumberSystem.multiply(DefaultNumberSystem.java:166)
	at tech.units.indriya.internal.function.calc.Calculator.multiply(Calculator.java:114)
	at tech.units.indriya.function.PowerOfIntConverter.convertWhenNotIdentity(PowerOfIntConverter.java:151)
	at tech.units.indriya.function.AbstractConverter.convert(AbstractConverter.java:236)
	at tech.units.indriya.AbstractQuantity.to(AbstractQuantity.java:199)
```

**Comment by andi-huber** [comment]
Could be considered correct behavior. Or what would you expect instead?

**Comment by DrDaleks** [comment]
In mathematical terms, isn't infinity always infinity (and therefore returned as such) ? The only caveat would be to account for sign (in case a conversion happens to inverse it)

In any case, getting a NumberFormatException isn't logical here. IllegalArgument perhaps (much further upstream) if you do consider this bad behaviour. But going through the inner guts indicates a missing corner case.

**Comment by keilw** [comment]
It really is a corner case, @andi-huber do you see a realistic chance to deal with that in classes like Calculator, or is it mostly up to `BigDecimal` anyway and we just have to accept it?

**Comment by andi-huber** [comment]
Agreed, if there are no side-effects, we could consider having Quantities.getQuantity(Double.POSITIVE_INFINITY,  ...) throw an IllegalArgumentException.

Just to be clear on infinities: we cannot do any arithmetic on them, hence its sane to not allow numbers that do not represent finite values.

I'll see what I can do, thx for spotting this.

**Comment by keilw** [comment]
Ok thanks, I think `IllegalArgumentException` is appropriate as we throw it in other places in similar situations.

**Comment by DrDaleks** [comment]
No worries. Not sure why returning infinity wouldn't be an option (that's more checks on client side), but the illegal argument is also a valid approach

**Comment by andi-huber** [comment]
eg. not defindedinf + (-inf)

**Comment by andi-huber** [comment]
For any call to `Quantities.getQuantity(Number amount, Unit unit)`, given `amount` is passed over to the configured `NumberSystem` where it is now _narrowed_. This allows us to do a check for finite numbers within our `DefaultNumberSystem`. If a non-finite number is discovered, we throw an `IllegalArgumentException`. 

Users may provide their own `NumberSystem` to override this behavior.
