### ISSUE TITLE
Adding celsius fails

### ISSUE THREAD

**Issue by schophil** [unitsofmeasurement/indriya#288]
https://github.com/unitsofmeasurement/indriya/blob/9bd4b97507a60c847802ef09ecc15e6e32f40e9e/src/main/java/tech/units/indriya/quantity/NumberQuantity.java#L171

```
        Quantity<Temperature> temp1 = Quantities.getQuantity(6, Units.CELSIUS, Quantity.Scale.RELATIVE);
        Quantity<Temperature> temp2 = Quantities.getQuantity(20, Units.CELSIUS, Quantity.Scale.RELATIVE);

        System.out.println(temp1);
        System.out.println(temp2);
        System.out.println(temp1.add(temp2));
```

Result:
```
6 ℃
20 ℃
12 ℃
```

I think it is caused by the `this.getValue()` on line 171. 
Shouldn't it be `that.getValue()`?

**Comment by andi-huber** [comment]
Yup, thanks for spotting this!
