### ISSUE TITLE
Converting the unit of relative quantities always yields absolute quantities, round trip with temperatures fails

### ISSUE THREAD

**Issue by ledan87** [unitsofmeasurement/indriya#295]
I stumpled upon an issue when writing api tests for indriya 2.0.3:

Consider the following (testng) unit test:

```java
...
import static org.testng.Assert.*;
import static tech.units.indriya.unit.Units.*;
...

@Test
public void convertRelativeTemperaturesRoundTrip() {

      Quantity<Temperature> celsiusRelative = Quantities.getQuantity(BigDecimal.valueOf(1), CELSIUS, Quantity.Scale.RELATIVE);
      Quantity<Temperature> kelvinRelative = celsiusRelative.to(KELVIN);

     // this test is already failing, as the Scale is absolute
      assertEquals(kelvinRelative, Quantities.getQuantity(BigDecimal.valueOf(1), KELVIN, Quantity.Scale.RELATIVE));

      Quantity<Temperature> roundTrip = kelvinRelative.to(CELSIUS);
      // this one fails as well, as the quantity of roundTrip is now -272.15 °C
      assertEquals(celsiusRelative, roundTrip);

}
```

It seems that the wrong factory method is called in AbstractQuantity.to(Unit)

Cheers,
Daniel

**Comment by keilw** [comment]
This could be related to other calculation issues and peculiarities we stumbled over after the 2.0.3 changes. @andi-huber would you also have a look at this please together with #294? Thanks.

**Comment by andi-huber** [comment]
2 observations regarding these tests:
1) The scope information is held by Quantities not Units. 
2) For Quantities of KELVIN there is no distinction between RELATIVE and ABSOLUTE, they are the same. So I think KELVIN RELATIVE is always converted to KELVIN ABSOLUTE implicitely. (not sure if this should be considered a bug)
2) The conversion of a Quantity to a different Unit will always implicitly convert to ABSOLUTE scope. (not a bug, but I guess also not documented)

**Comment by andi-huber** [comment]
That said, the tests above seem intuitively correct to me and maybe we can improve the library such that these do work,

**Comment by keilw** [comment]
What's the "scope", do you mean "scale"?

**Comment by andi-huber** [comment]
ah sorry, yes scale

**Comment by ledan87** [comment]
> 
> 
> That said, the tests above seem intuitively correct to me and maybe we can improve the library such that these do work,

I think that only requires calling the right factory method for Quantities in AbstractQuantity.to(Unit unit) => line 207. 

I just rolled back from 2.03. to 2.0 and check the conversion for T_rel = 1 °C to KELVIN. It yielded 274.15 K, which is also not correct. 

In 2.0.3 the result for the conversion  is 1 °C => 1 K, but the result is absolute and this is leading to errors downstream. When converting the units of relative quantities, the result should always be a relative quantity.

**Comment by andi-huber** [comment]
@ledan87 thanks for spotting this. I have supposedly fixed this one. If you find new issues, don't hesitate to let us know.
