### ISSUE TITLE
Addition and subtraction in *Quantity classes don't handle large differences in prefixes well

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#30]
If there is a large difference in the metric prefixes such that overflow becomes possible, the implementation of the addition and the subtraction is too naive.

Example using IntegerQuantity:
2 YΩ - 1 yΩ = 2 YΩ (correct)
2 yΩ - 1 YΩ = -2147483645 yΩ (incorrect, should have been -1 YΩ)

The implementations should cast the values to the largest metric prefix, not the metric prefix of the first element.

**Comment by keilw** [comment]
Thanks for raising this. Note, `IntegerQuantity` using just integer values is always a bit risky. Since  yΩ is a submultiple, casts are involved but the result is still an `Integer` which is why precision can be lost in any case. Do you have some JUnit tests that can replicate this? And did you also try types with higher precision like `DoubleQuantity `or `DecimalQuantity`?

**Comment by filipvanlaenen** [comment]
Actually, there's a bit more to it than just this.

Look at this:
```java
private static final IntegerQuantity<ElectricResistance> ONE_OHM = new IntegerQuantity<ElectricResistance>(Long.valueOf(1).intValue(), Units.OHM);
private static final IntegerQuantity<ElectricResistance> ONE_MILLIOHM = new IntegerQuantity<ElectricResistance>(Long.valueOf(1).intValue(), MetricPrefix.MILLI(Units.OHM));

System.out.println(ONE_OHM.add(ONE_MILLIOHM));
System.out.println(ONE_MILLIOHM.add(ONE_OHM));
```

This will produce the following result:
```
1 Ω
1001 mΩ
```

For the integer types, casting to the largest multiple may not be the best solution.

**Comment by filipvanlaenen** [comment]
Maybe we should try and fill out the following table of the expected behavior for IntegerQuantity:

| a + b, b↓, a→ | 1 YΩ  | 1 Ω   | 1 mΩ | 1 yΩ |
|-------------------:|:--------:|:--------:|:--------:|:--------:|
| 1 YΩ               | 2 YΩ | 1 YΩ | 1 YΩ  | 1 YΩ | 
| 1 Ω                 | 1 YΩ | 2 Ω   | 1001 mΩ | 1 Ω |
| 1 mΩ              | 1 YΩ | 1001 mΩ | 2 mΩ | 1 mΩ |
| 1 yΩ               |  1 YΩ | 1 Ω | 1 mΩ | 2 yΩ |

**Comment by keilw** [comment]
Though I think with IntegerQuantity the first one behavior seems correct. MILLI results in a decimal fraction which for Integer values is normally cut away. The second looks OK, full multiples without decimal parts are treated correctly. 
It would be nice to add some JUnit tests for those. The overall test coverage  could be better.

**Comment by filipvanlaenen** [comment]
Does that mean that you would expect the following behavior?

| a + b, b↓, a→ | 1 YΩ  | 1 Ω   | 1 mΩ | 1 yΩ |
|-------------------:|:--------:|:--------:|:--------:|:--------:|
| 1 YΩ               | 2 YΩ | (TBD, currently -2147483648 Ω) | (TBD)  | (TBD) | 
| 1 Ω                 | 1 YΩ | 2 Ω   | 1001 mΩ | (TBD) |
| 1 mΩ              | 1 YΩ | 1 Ω | 2 mΩ | (TBD) |
| 1 yΩ               |  1 YΩ | 1 Ω | 1 mΩ | (TBD) |

**Comment by keilw** [comment]
I am not a professional electro engineer like my late father was ;-)
`YΩ` would be `YOTTAOHM` I guess? I'm not sure, if it works for IntegerQuantity at all, which is likely why you end up with -2147483648. which must be the smallest or biggest number `Integer` can hold.
1 YΩ would be 1000000000000000000000000 Ω, thus adding 1 YΩ I'd expect it to be 1000000000000000000000001. However, unless BigInteger or BigDecimal are used, the other data types are probably not likely to handle that.

**Comment by filipvanlaenen** [comment]
I think the first table gives the most intuitive results. The implementation would be to cast the values to the smallest multiple, unless that results in an overflow, in which case the values have to be cast to the largest multiple.

I also think people may get annoyed when they see that 1 Ω + 1 mΩ ≠ 1 mΩ + 1 Ω.

The examples in the table may be a bit sought, but something like 2 Ω + 500 mΩ would be a natural thing to calculate. Currently, it returns 2 Ω. We shouldn't force the user to sort according multiple in order to get the correct result, which is 2,500 mΩ. (But I also recognize you shouldn't be using integers for such calculations to begin with.)

I did some tests with FloatQuantity too yesterday, and got some infinities where I would have expected e.g. 1 YΩ.

**Comment by keilw** [comment]
What about DecimalQuantity? We should still support all the types JDK does, but for some a warning on precision is a good idea.

**Comment by keilw** [comment]
(In reply to comment #7)
> I think the first table gives the most intuitive results. The implementation
> would be to cast the values to the smallest multiple, unless that results in an
> overflow, in which case the values have to be cast to the largest multiple.
> 
> I also think people may get annoyed when they see that 1 Ω + 1 mΩ ≠ 1 mΩ + 1 Ω.
> 
> The examples in the table may be a bit sought, but something like 2 Ω + 500 mΩ
> would be a natural thing to calculate. Currently, it returns 2 Ω. We shouldn't
> force the user to sort according multiple in order to get the correct result,
> which is 2,500 mΩ. (But I also recognize you shouldn't be using integers for
> such calculations to begin with.)
> 
> I did some tests with FloatQuantity too yesterday, and got some infinities where
> I would have expected e.g. 1 YΩ.

Indeed that might seem a little weird, but how should we try to address that? Each operation in a chain that could also be add().subtract().add()... can only look at the two arguments involved there.
add() and subtract() need to convert before the actual operations.

**Comment by keilw** [comment]
Some if not all of these should use BigIntegerQuantity, see https://github.com/unitsofmeasurement/indriya/issues/31

**Comment by filipvanlaenen** [comment]
I've started to wonder whether the converters should throw an Exception (e.g. ArithmeticException) when an overflow occurs, or alternatively, that we create a ExactConverters to do that.

**Comment by keilw** [comment]
I certainly would not create something like `ExactConverter` in the API, but treating operations differently was an option. The somewhat stricter divide() or multiply() operations of `BigInteger` also show, that e.g. in one test where `IntegerQuantity` would allow returning a double, `BigIntegerQuantity` doesn't.
I would not throw an exception, but maybe for the operation that Java just turns to `Integer.MIN_VALUE` like in `yottaOhmTest` there I could imagine throwing an overflow exception.

**Comment by filipvanlaenen** [comment]
I tried to implement a solution, see https://github.com/filipvanlaenen/indriya/tree/IntegerQuantityAddition

If it looks OK, I can make a pull request, and use it as a template for the other primitive integer types.

**Comment by keilw** [comment]
Thanks, if everything compiles and JUnit tests produce the expected result, please do. Btw. do you really need `ComparableQuantity `internally, or can the cast be avoided? The `NumberQuantity `factory methods automatically return a `ComparableQuantity`, so the cast seems unnecessary if you only access methods of `Quantity`.

**Comment by filipvanlaenen** [comment]
There were some more corner cases, and I changed the logic to handle overflows through an ArithmeticException. Also removed the cast. Pull request submitted.

**Comment by keilw** [comment]
Thanks, I'll check them out and merge after review, if you can, please also feel free to add @otaviojava as reviewer for this or future PRs.

**Comment by filipvanlaenen** [comment]
Submitted a pull request porting the changes from IntegerQuantity to LongQuantity, and tried to find out how I can add @otaviojava as a reviewer, but I think I don't have the right permissions to do that.

**Comment by keilw** [comment]
Is https://github.com/unitsofmeasurement/indriya/pull/57 still part of addressing this issue or something else?

**Comment by filipvanlaenen** [comment]
Yes, #57 is. There are more classes that need to fixed (all of them slightly different).

**Comment by keilw** [comment]
Thanks, the "Bug Bounty" behind https://github.com/unitsofmeasurement/unit-api/issues/87 is a little more important. I made use of the special converter retrieval between AbstractUnit and AbstractConverter, but it looks like the full precision of RationalConverter is required at least for every Prefix. If this can be somehow derived in AbstractUnit like @andi-huber suggested, it may be possible to keep both Prefix and `MetricPrefix` or `BinaryPrefix` in the API/SPI.

**Comment by filipvanlaenen** [comment]
@keilw I know the bug bounty on the other issue is more important, but since @andi-huber has a much shorter turn-around time than I have, I think it's better that I stay a bit away from it :-)

**Comment by keilw** [comment]
Could you create a follow-up ticket to split it into smaller tickets?
