### ISSUE TITLE
Exploring possible PPC build

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#304]
Similar to https://github.com/unitsofmeasurement/unit-api/issues/210 we might consider a PPC64 build, but currently the result of the Travis build for PPC64 https://travis-ci.org/github/unitsofmeasurement/indriya/jobs/728783441 does not look so good.
Indriya has the Maven Toolchain build as a mandatory requirement for the Multi-Release-JAR, and unlike Intel/AMD the `JAVA_HOME` environment variable is not set: `Warning: JAVA_HOME environment variable is not set.`
@sanjay-cpu any thoughts here?
You're welcome to have a look at the branch and see, if you could make something out of it, as long as the Toolchain works, it's more important than PPC.

**Comment by keilw** [comment]
I found a workaround by adding `JAVA_HOME` based on a known "jvm" folder in the case of PPC64, a bit similar to the MAVEN_HOME but without installing another JDK.

**Comment by sanjay-cpu** [comment]
> Similar to [unitsofmeasurement/unit-api#210](https://github.com/unitsofmeasurement/unit-api/issues/210) we might consider a PPC64 build, but currently the result of the Travis build for PPC64 https://travis-ci.org/github/unitsofmeasurement/indriya/jobs/728783441 does not look so good.
> Indriya has the Maven Toolchain build as a mandatory requirement for the Multi-Release-JAR, and unlike Intel/AMD the `JAVA_HOME` environment variable is not set: `Warning: JAVA_HOME environment variable is not set.`
> @sanjay-cpu any thoughts here?
> You're welcome to have a look at the branch and see, if you could make something out of it, as long as the Toolchain works, it's more important than PPC.

Hi @keilw , Yes, you need to point the JAVA_HOME to proper jvm folder. Thanks !!
