### ISSUE TITLE
DefaultNumberSystem isLessThanOne is inverted

### ISSUE THREAD

**Issue by raynigon** [unitsofmeasurement/indriya#314]
The `isLessThanOne` in the `DefaultNumberSystem` is inverted.
Current behaviour:
- `new DefaultNumberSystem().isLessThanOne(1.0)` returns true
- `new DefaultNumberSystem().isLessThanOne(0.9)` returns false
Expected behaviour:
- `new DefaultNumberSystem().isLessThanOne(1.0)` returns false
- `new DefaultNumberSystem().isLessThanOne(0.9)` returns true

**Comment by andi-huber** [comment]
Thanks for spotting this one! 
Fixed in current 'master'.
