### ISSUE TITLE
Killing Travis-CI

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#326]
Unfortunately before forcing everyone to travis-ci.com Travis-CI already fails to work properly.
The build fails with a bogus error
`Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com.`

We have no time to waste with this, I'm afraid we have to kill every Travis instance because there is no guarantee, this does not happen more often for a different JDK version and we don't need to build it on every single JDK out there. JDK 14 works on Circle-CI and unless that also starts misbehaving or stiffeling developers in a similar way, we just won't use Travis-CI anymore.

**Comment by andi-huber** [comment]
Not sure how Travis-CI is setup for this project in detail, but note:  we might just have burnt through all the monthly _Credits_.
https://www.travis-ci.com/plans

**Comment by keilw** [comment]
No unless these credits and plans affect just a single JDK, but I have no intention to fiddle with the Travis-CI file and manually reduce the number of JDKs because of that. It only failed on JDK 14 but there is no guarantee, that doesn't happen for a different one, so that makes the entire Travis option useless and more of a burden, so we will shut it down, because we do not have any budget to pay for it either (unless we got donations some day for that by fans of Travis-CI? ;-)

**Comment by andi-huber** [comment]
Ok, I see. Thx for clarifying.

**Comment by keilw** [comment]
So it's disabled for automatic build. Let's wait for the forced migration of everything to travis-ci.com, but until we know how the quota really works there the Travis instance should only be a manual-build when a test across different JDKs is desired, e.g. if a new JDK comes up etc.
