### ISSUE TITLE
Apply flyweight pattern to Calculator

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#330]
The `Calculator` class has static `of()` method and private methods but it is not final and does not prevent calling the constructor either. It does not make sense there, so it should be made a true singleton.

**Comment by andi-huber** [comment]
Calculator is not designed to be a singleton. Instead each calculation gets its own (throw away) calculator instance for thread safety.

However, no objections to hide the default (no arg) constrctor and make the class final.

**Comment by keilw** [comment]
Singleton may be the wrong term but applying the pattern using `of()` instead of the contstructor should be encouraged.
