### ISSUE TITLE
Inconsistent versions in dependencies

### ISSUE THREAD

**Issue by mipastgt** [unitsofmeasurement/indriya#341]
Indriya depends on unit-api 2.1.2 and also on uom-lib-common 2.1 but this lib still depends on the old unit-api 2.0 and not 2.1.2. Shouldn't that be made consistent.
<img width="376" alt="Bildschirmfoto 2021-04-05 um 12 52 45" src="https://user-images.githubusercontent.com/16735714/113567865-b62cd780-960f-11eb-9b46-34fdf15d1e41.png">

**Comment by keilw** [comment]
There's no need to publish uom-lib-common with a new number just for the sake of it. The dependency chain shows other indirect dependencies like `javax.inject` that we hope to get rid of eventually (or upgrade to `jakarta.inject`) but it does not cause problems building or anywhere else either. The older version got ignored/overriden by the later one, so there is no negative impact or actual duplication of the dependencies anywhere, the latest one defined by Indriya is used.
There are other `uom-lib` components that should be updated and when they get a new release, it likely makes sense to tag everything in that repo, but before that it would be an overkill.
