### ISSUE TITLE
Should we keep the "virtual" tec domain?

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#35]
Before the "tech" domain became available after March 2015 the RI and TCK used a "virtual" domain name `units.tec` I registered instead. Since then `units.tech` is also registered. While the "tec" domain is fairly cheap, it won't work as a URL, it is just virtual. 
Should we use the 2.0 release and switch to `units.tech` instead?

Depending on the choice for Indriya, the new TCK would also match its package namespace.

**Comment by keilw** [comment]
A) switch to units.tech

**Comment by duckAsteroid** [comment]
A

**Comment by keilw** [comment]
Thanks

**Comment by wick3dshadow** [comment]
Option A looks great to me.

**Comment by keilw** [comment]
Thanks everyone for voting. Except the TCK usage project all relevant artifacts of JSR 385 have now been migrated.
