### ISSUE TITLE
Support parsing quantity strings for specific locale

### ISSUE THREAD

**Issue by wborn** [unitsofmeasurement/indriya#351]
It would be helpful if support is added for parsing strings using a specific locale by having a method similar to [Quantities.getQuantity(CharSequence)](https://github.com/unitsofmeasurement/indriya/blob/c7b04bd29dc172677c77d2490962077307c3f887/src/main/java/tech/units/indriya/quantity/Quantities.java#L83) that has an additional `Locale` parameter.

It could then for instance create a `SimpleQuantityFormat` for that locale which would use the specified `Locale` in [`SimpleQuantityFormat.parse`](https://github.com/unitsofmeasurement/indriya/blob/c7b04bd29dc172677c77d2490962077307c3f887/src/main/java/tech/units/indriya/format/SimpleQuantityFormat.java#L201) for parsing strings by creating a `NumberFormat` based on the specified `Locale` instead of the default `Locale`. The default locale can change depending on what is configured in the OS or if code calls `Locale.setDefault`.

Besides being able to have more deterministic parsing behavior, it can also be used when users enter a String in a UI based on their own `Locale` (different from the default JVM Locale).

**Comment by keilw** [comment]
Please note, that already exists, but you should use `LocalUnitFormat` instead.
`Quantities.getQuantity(CharSequence)` is mainly a convenience method beside the actual factories like `getQuantity(Number, Unit)` so adding a locale-specific helper there I think would be an overkill.

You can use `ServiceProvider.current().getFormatService().getQuantityFormat("Local")` to get a localized `QuantityFormat` for the current locale. 
Everything else beyond that is possible via `NumberDelimiterQuantityFormat.Builder` also see #349 which was about passing a `CompactNumberFormat` beyond Java 12, but you can use that builder to create the `UnitFormat` and `NumberFormat` of your own choice, if those predefined via SPI are not sufficient.
Does this answer your question?

**Comment by keilw** [comment]
Btw @wborn I see you're based in the Netherlands, I understand @thodorisbais is now busy with other duties, but maybe if he can still help his JUG at least after COVID allows that again you may also get together e.g. at a MeetUp or something.

**Comment by wborn** [comment]
Thanks for your quick answers and showing me around the SPI @keilw. :+1:
The configuration options on the `NumberDelimiterQuantityFormat` look very promising.

We ran into some parsing issues of the new default locale dependent behavior of `Quantities.getQuantity` after upgrading openHAB from javax.measure 1.x to 2.x

Creating the following format seems to get back the more deterministic behaviour that was once provided by `tec.uom.se.quantity.Quantities.getQuantity`:

```java
            NumberDelimiterQuantityFormat format = new NumberDelimiterQuantityFormat.Builder()
                    .setNumberFormat(NumberFormat.getInstance(Locale.ENGLISH))
                    .setUnitFormat(SimpleUnitFormat.getInstance()).setLocaleSensitive(false).build();
```

If I use this format all the unit tests still succeed but that doesn't always guarantee the absence of issues. :innocent:

Do you think that would be very similar to using the `SimpleQuantityFormat` like used with `Quantities.getQuantity` or would we need to use other configuration options to prevent issues? This way it would also be easy to change the locale of the number format.

Also it is not really clear to me how the `localeSensitive` option is (or will be) used. I did not find any code that uses it. We probably need to set it to `false` when creating formats depending on a specific locale?

**Comment by keilw** [comment]
`SimpleUnitFormat` is completely locale-agnostic. And `localeSensitive` only returns true, if the `Locale` may influence the output or parsing for a particular format. So 
```
            NumberDelimiterQuantityFormat format = new NumberDelimiterQuantityFormat.Builder()
                    .setNumberFormat(NumberFormat.getInstance(Locale.ENGLISH))
                    .setUnitFormat(SimpleUnitFormat.getInstance()).setLocaleSensitive(false).build();
```
seems misleading, because localeSensitive there should be true, since you apply an `ENGLISH` `Locale`. 
I admit it is a bit tricky, because the NumberFormat unlike UnitFormat does not provide any proper information about the Locale it was created with.

**Comment by wborn** [comment]
Thanks for the info! I'll close the issue since I think it will work this way. :slightly_smiling_face:

**Comment by keilw** [comment]
Thanks for closing it, I made a small adjustion to use the flag of the UnitFormat, but as mentioned with a NumberFormat it is up to your code to tweak it and primarily a "warning sign" if you want, how that formatter behaves.
