### ISSUE TITLE
How SystemUnit is figured out?

### ISSUE THREAD

**Issue by kelemenb-ewit** [unitsofmeasurement/indriya#361]
I want to define units in Concentration<Volume>.
`CUBIC_METRE_PER_CUBIC_METRE` can be
 `AbstractUnit.ONE.alternate("m³/m³")` or `AlternateUnit.of(AbstractUnit.ONE, "m³/m³", null)`

But how can I define `CUBIC_CENTIMETRE_PER_CUBIC_METRE` (cm³/m³) to have system unit m³/m³? It is always "one" for me.

(Btw. how should I apply `"asType()`" for quantity` Concentration<Volume>`?)

Thanks!

**Comment by andi-huber** [comment]
For consistency there can only be one unit representing ONE. See also https://github.com/unitsofmeasurement/indriya/issues/338#issuecomment-791416311

**Comment by kelemenb-ewit** [comment]
Let me detail my problem. Let's assume we have introduced volumetric concentration with system unit m³/m³. Like this:

```java
Unit<Concentration<Volume>> CUBIC_METRE_PER_CUBIC_METRE =
            addUnit((Unit<Concentration<Volume>>) AlternateUnit.of(
                AbstractUnit.ONE, "m³/m³", null))
```

If I want to make cm³/m³ you might say I should do
```java
Unit<Concentration<Volume>> CUBIC_CENTIMETRE_PER_CUBIC_METRE_FALSE =
            CENTI(CUBIC_METRE_PER_CUBIC_METRE)
```

While the `CUBIC_CENTIMETRE_PER_CUBIC_METRE_FALSE.getSystemUnit()` show the correct "m³/m³", this is not the thing I want, as this is "c(m³/m³)".

Instead, what I do is
```java
        Unit<Volume> cubicCentriMetre = new ProductUnit<>(CENTI(METRE).pow(3));
        Unit<Volume> cubicMetre = new ProductUnit<>(METRE.pow(3));
        Unit<Concentration<Volume>> CUBIC_CENTIMETRE_PER_CUBIC_METRE_RIGHT =
            new ProductUnit<>(cubicCentriMetre.divide(cubicMetre));
```

But here the `CUBIC_CENTIMETRE_PER_CUBIC_METRE_RIGHT.getSystemUnit()` returns "one".

How can I achieve to have systemUnit for _cm³/m³_ of type _m³/m³_ instead of type _one_?

Thanks!

**Comment by andi-huber** [comment]
Both `cm³/m³` and `m³/m³` are dimensionless _Units_. These are indistinguishable from `10^-6 x AbstractUnit.ONE` or ` AbstractUnit.ONE` respective. Hence, the framework always simplifies dimensionless Units to `AbstractUnit.ONE` (scaled if required).

**Comment by andi-huber** [comment]
In other words: `AlternateUnit.of(AbstractUnit.ONE, "m³/m³", null))` is not a supported idiom.

**Comment by kelemenb-ewit** [comment]
Thank you for your fast reply, but I sill don't get it. What about
```java
RADIAN = addUnit(AlternateUnit.of(AbstractUnit.ONE, "rad", "Radian"), Angle.class)
```
can be found in `tech.units.indriya.AbstractSystemOfUnits`?

I can say `KILO(RADIAN)` and the system unit of it is `RADIAN`, that seams to be a supported and reasonable way to go.

**Comment by andi-huber** [comment]
Fair point. But `RADIAN` is a 'pseudo' unit, which is treated as its own thing, which needs explicit conversion to Unit `AbstractUnit.ONE` if desired. However with `m³/m³`, you are using a product/division composition of the `METRE` Unit. 

You can however define your own concentration unit `m³/m³` by the name of `CUBIC_CENTIMETRE_PER_CUBIC_METRE`, but only as a 'pseudo' unit, not based on the built-in `METRE` Unit. But that's likely not really what you want, as you can no longer do any consistent conversion into other units.

**Comment by kelemenb-ewit** [comment]
To be a pesudo unit is perfectly okay for me right now. So assuming that, the question still stands:

> How can I achieve to have systemUnit for cm³/m³ of type m³/m³ instead of type one?

(The same way as the system unit of centiradian is radian.)

**Comment by andi-huber** [comment]
Well `cm³/m³` would be its own unit as well, with no relationship to `m³/m³`.

**Comment by kelemenb-ewit** [comment]
I understand your point, still I don't like this answer. :)
Thanks anyway!
