### ISSUE TITLE
Comparing a Quantity of `Double.MAX_VALUE` with a `BigDecimal` value gives unexpected results 

### ISSUE THREAD

**Issue by t-ober** [unitsofmeasurement/indriya#362]
Calling  `Quantities.getQuantity(Double.MAX_VALUE, Unit).isLessThan()` with a `BigDecimal` number always returns `true`.
This only happens when the `BigDecimal` value is constructed with a double or a comma-separated String. 

Code to reproduce: 

```
ComparableQuantity<ElectricCurrent> maxValue = Quantities.getQuantity(Double.MAX_VALUE, tech.units.indriya.unit.Units.AMPERE);
ComparableQuantity<ElectricCurrent> value = Quantities.getQuantity(new java.math.BigDecimal("1.1"), tech.units.indriya.unit.Units.AMPERE);
System.out.println(maxValue.isLessThan(value));
```  

This seems highly unintuitive. Is this a bug or am I missing something?

**Comment by andi-huber** [comment]
I believe this is fixed since https://github.com/unitsofmeasurement/indriya/commit/6b70a579f7221db0254c8ced4f52842d01231d0d

**Comment by keilw** [comment]
I scoped it for [2.1.3](https://github.com/unitsofmeasurement/indriya/milestone/9), if it was already fixed please verify and consider closing it. The other issues are finished or mostly involve documentation.

**Comment by t-ober** [comment]
This indeed seems to be resolved! 
Thanks for the fast reply and of course for maintaining this very helpful project 🙂
