### ISSUE TITLE
Names of derived units

### ISSUE THREAD

**Issue by XXLuigiMario** [unitsofmeasurement/indriya#367]
This is a revisit of #271.
Many units are without their names because they're derived from others. This greatly reduces the usefulness of Unit#getName.

These all return `null`:
`Units.GRAM.getName()` (expected: `Gram`)
`Units.METRE.prefix(MetricPrefix.KILO).getName()` (expected: `Kilometre`)
`Units.CUBIC_METRE.getName()` (expected: `Cubic metre`)
... and so on and so forth.

**Comment by keilw** [comment]
Except for `Units.METRE.prefix(MetricPrefix.KILO).getName()` (there's an operation involved and it therefore won't even either name or symbol) the other two can get a name inside the `Units` collection.

**Comment by keilw** [comment]
Now all units defined inside `Units` got a name.
