### ISSUE TITLE
Make `AbstractUnits.ONE` a `Unit<AmountOfSubstance>`

### ISSUE THREAD

**Issue by GregJohnStewart** [unitsofmeasurement/indriya#368]
I believe the `AbstractUnits.ONE` should be a unit that describes `AmountOfSubstance`, similarly to how `Units.Mole` is.

Might also make sense to make `k`, 'm', 'g`, etc units as well, but that can be a different ask.

**Comment by keilw** [comment]
Sorry but that request seems odd to near spam. 
k, m, g, etc. ARE units already and there is no justification for turning the `Dimensionless` constant unit `AbstractUnit.ONE` to something else like `AmountOfSubstance`.

**Comment by andi-huber** [comment]
We might consider physical quantities to form a _commutative group_ under multiplication. `AbstractUnits.ONE` is special as with `Quantities.getQuantity(1, AbstractUnits.ONE)` we identify the _identity element_ of this group.

Turns out, there can be only one such special _Unit_ instance, for the framework to produce consistent results. Hence its unlikely we ever need to change how its currently implemented.

**Comment by keilw** [comment]
Thanks @andi-huber for chipping in, if any constant (that is not already part of the natural constants) was useful we might consider that but under a different name.
`KILOGRAM, METRE, GRAM` (in certain systems while that is a bit redundant to kg) are all well-defined units, hence no need to change that seems necessary.

**Comment by andi-huber** [comment]
Note: the name `AbstractUnit.ONE` might be a bit misleading: it does **not** mean a 'quantity of one' but rather a dimension-less unit aka `Unit<Dimensionless>`.

**Comment by GregJohnStewart** [comment]
Agreed, it is misleading then.

I feel like these was some misconception on my "k, m, g" thing as well, which was not my main ask. My note there was that it might be useful to describe "one thousand of something", etc.

**Comment by keilw** [comment]
I think the closest might be a quantity type `Each` in [uom-domain/retail/quantity](https://github.com/unitsofmeasurement/uom-domain/tree/master/retail/src/main/java/tech/uom/domain/retail/quantity)
ICU4J introduced constant units (or non-units) like BASE, etc. in the [NoUnit](https://javadoc.io/static/com.ibm.icu/icu4j/70.1/com/ibm/icu/util/NoUnit.html) class.
