### ISSUE TITLE
[Request] More guide (less ukrain stuff)

### ISSUE THREAD

**Issue by LSafer** [unitsofmeasurement/indriya#379]
I know you really feel bad for ukrain but I feel you should focus on adding 
more user-guides. I really didn't see any `Getting Started` stuff and this is 
the first thing people should see when deciding to use a library

I am posting this since you look like you have plenty of time to put ukrain everywhere.

**Comment by desruisseaux** [comment]
On my side I'm rather glad of supports for Ukraine. But anyway, it is up to everyone to choose their own priorities.

**Comment by keilw** [comment]
Thanks @andi-huber for closing this. The releases have codenames for quite a while, there was also a "Hidden Figures" release and so far there was no post by White Supremacists about that, but there is always a first time for everything. It is ridiculous, given Github's parent Microsoft completely left Russia and Github itself coloured its mascot and site in Ukraine's colour for many months. Blocked this troll.

**Comment by keilw** [comment]
And as for guides, everyone is welcome to contribute instead of spreading hate.
