### ISSUE TITLE
Release 2.2 missing on Maven central

### ISSUE THREAD

**Issue by J-N-K** [unitsofmeasurement/indriya#400]
Title says it all. According to https://central.sonatype.com/search?q=indriya the latest release is 2.1.4 while GitHub shows 2.2 since some days.

**Comment by keilw** [comment]
Seems there was a problem staging. I.E. the Common Library was not visible yet, which also caused one or the other build to fail.
Thanks for pointing it out.

**Comment by keilw** [comment]
Check later today, it is already released, but it takes a few hours till all the mirrors pick it up.
