### ISSUE TITLE
	Explicit visibility for ProductUnit.getPowInstance (advised by Codacy)

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#6]
See https://github.com/unitsofmeasurement/uom-se/pull/180
Rest under https://github.com/unitsofmeasurement/indriya/issues/7

**Comment by Pr0methean** [comment]
This commit was designed purely to satisfy Codacy; feel free to suppress Codacy's warning about implicit package-local access if there's a good reason for the affected methods not to be public or protected.

**Comment by keilw** [comment]
Thanks, it is consistent with the other implementations, but here as you may have seen the static accessors were renamed to `ofX()` already. No strong need to do it in all other implementations, as one usually does not call them directly but via `Unit.multiply()` or similar. At the moment I'm hesitant to apply all the AbstractUnit changes here. Among possible goals for  a new version of the JSR is https://github.com/unitsofmeasurement/unit-api/issues/38 which hints that if somehow possible without incompatibilities or twists, we could make one implementation co-exist with others under the right circmumstances even in the same module or class path.

**Comment by keilw** [comment]
@Pr0methean You are more than welcome to join the JCP e.g. as Associate btw, if you consider helping Indriya and an upcoming new version of the JSR.

**Comment by Pr0methean** [comment]
Sounds great! I'll take a look at Indriya some time in the next few weeks.
