### ISSUE TITLE
Improve addition BigIntegerQuantity

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#66]
It should return 1,001 mΩ on 1 Ω + 1 mΩ.

**Comment by filipvanlaenen** [comment]
OK. I was planning to fix it myself, but you're probably faster :-)

**Comment by andi-huber** [comment]
;)
Please feel free to review or improve the commit which addresses this issue:
https://github.com/unitsofmeasurement/indriya/pull/65/commits/6cea95c958dbad1f7e3d0d8a6fbdfec2b2db7f21

**Comment by andi-huber** [comment]
I forgot to do the changes for subtraction as well, working on it ...

**Comment by andi-huber** [comment]
Ok, apart from typos I corrected later, this commit should fix the issue:
https://github.com/unitsofmeasurement/indriya/pull/65/commits/6d98699afbae544a38f293fc54c27de0d3cd165f

For reference: it's all stacked up with PR #65

**Comment by andi-huber** [comment]
Changes merged into master. Feel free to improve on that, or close this issue. 
I'm done for today.
