### ISSUE TITLE
Create a “Instructions to the Developers” page

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#72]
It should include:
* Convention on how to relate commits and pull requests to issues
* Setting up the code formatter in Eclipse

**Comment by andi-huber** [comment]
I'm also curious about java-doc conventions:
- author
- version
- since
- when to override java-doc of inherited methods

**Comment by keilw** [comment]
Not sure, if you want this in a wiki here, or as part of the https://github.com/unitsofmeasurement/uom-guide ?

**Comment by keilw** [comment]
I removed 2 inactive members from https://www.gitbook.com/@unitsofmeasurement/teams so up to 2 in addition to EG members @otaviojava and @duckAsteroid may also join via GitBook if you have accounts, please let me know. The others can of course use GitHub, most documents are plain MD files that work in the GitHub editor, too.

**Comment by filipvanlaenen** [comment]
I meant the Wiki. I've started a page here: https://github.com/unitsofmeasurement/indriya/wiki/Instructions-to-Contributors
