### ISSUE TITLE
Incorrect multiplication in LongQuantity

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#74]
LongQuantity doesn't multiply the unit. E.g. `2 Ω × 2 Ω` results into `4 Ω`, where it should be `4 Ω²`.

Pull request should come in a few minutes.

Needs #67

**Comment by filipvanlaenen** [comment]
Did a quick check, and it looks like `LongQuantity` is the only quantity type with this type of bug.

**Comment by keilw** [comment]
IC, any chance to check it against uom-se? I know @andi-huber and you contributed a lot here but if it was an old bug, at least uom-se should be fixed, too until JSR 385 goes Final.

**Comment by filipvanlaenen** [comment]
Same bug there: https://github.com/unitsofmeasurement/uom-se/issues/195

**Comment by keilw** [comment]
Thanks, think you could backport the PR? If it also affects unit-ri, why not offer a patch, but it has the lowest priority also because for certain numbers (maybe not so much for `long `though) there's always a precision loss compared to `BigDecimal` or `BigInter`.

**Comment by keilw** [comment]
Needs #67

**Comment by filipvanlaenen** [comment]
Closing this issue. The backporting to uom-se has its own issue there.
