### ISSUE TITLE
Rename PowersOf*Converter to PowerOf*Converter

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#76]
It's a minor tweak, so hope it won't offend anybody? ;-)
Although it is mainly an internal representation there, Guava contains a `PowerOfTwoStriped` class for concurrency support. Each converter only performs a single `PowerOf()` operation, it may be chained using `concatenate()` but the converter as such only does a single conversion, therefore PowerOfPiConverter or PowerOfIntConverter sounds more natural.

**Comment by andi-huber** [comment]
Sounds reasonable!

**Comment by keilw** [comment]
Thanks for the quick response
