### ISSUE TITLE
FloatQuantity.multiply(Number) shouldn't multiply the unit with the number too

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#98]
Discovered while working on #20.

Observed behavior: 2 × 2 Ω = 4 Ω×2.
The correct result is: 2 × 2 Ω = 4 Ω.

**Comment by keilw** [comment]
Thanks, it seems fixed here, or is there still something missing?
I also had to backport it to the old **units-ri** and **uom-se**. We may release each one for critical inconsistencies. I don't expect any further optimization or improvement like the whole arithmetic discussion there however, that is entirely up to version 2.

**Comment by filipvanlaenen** [comment]
Yes, it's fixed now since the unit test runs fine.
